// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module real_converter_real_converter_Pipeline_FB_ROW_FB_COL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        R_fb_re_address0,
        R_fb_re_ce0,
        R_fb_re_we0,
        R_fb_re_d0,
        R_fb_im_address0,
        R_fb_im_ce0,
        R_fb_im_we0,
        R_fb_im_d0,
        R_local_re_address0,
        R_local_re_ce0,
        R_local_re_q0,
        R_local_re_address1,
        R_local_re_ce1,
        R_local_re_q1,
        R_local_re_1_address0,
        R_local_re_1_ce0,
        R_local_re_1_q0,
        R_local_re_1_address1,
        R_local_re_1_ce1,
        R_local_re_1_q1,
        R_local_re_2_address0,
        R_local_re_2_ce0,
        R_local_re_2_q0,
        R_local_re_2_address1,
        R_local_re_2_ce1,
        R_local_re_2_q1,
        R_local_re_3_address0,
        R_local_re_3_ce0,
        R_local_re_3_q0,
        R_local_re_3_address1,
        R_local_re_3_ce1,
        R_local_re_3_q1,
        R_local_re_4_address0,
        R_local_re_4_ce0,
        R_local_re_4_q0,
        R_local_re_4_address1,
        R_local_re_4_ce1,
        R_local_re_4_q1,
        R_local_re_5_address0,
        R_local_re_5_ce0,
        R_local_re_5_q0,
        R_local_re_5_address1,
        R_local_re_5_ce1,
        R_local_re_5_q1,
        R_local_re_6_address0,
        R_local_re_6_ce0,
        R_local_re_6_q0,
        R_local_re_6_address1,
        R_local_re_6_ce1,
        R_local_re_6_q1,
        R_local_re_7_address0,
        R_local_re_7_ce0,
        R_local_re_7_q0,
        R_local_re_7_address1,
        R_local_re_7_ce1,
        R_local_re_7_q1,
        R_local_im_address0,
        R_local_im_ce0,
        R_local_im_q0,
        R_local_im_address1,
        R_local_im_ce1,
        R_local_im_q1,
        R_local_im_1_address0,
        R_local_im_1_ce0,
        R_local_im_1_q0,
        R_local_im_1_address1,
        R_local_im_1_ce1,
        R_local_im_1_q1,
        R_local_im_2_address0,
        R_local_im_2_ce0,
        R_local_im_2_q0,
        R_local_im_2_address1,
        R_local_im_2_ce1,
        R_local_im_2_q1,
        R_local_im_3_address0,
        R_local_im_3_ce0,
        R_local_im_3_q0,
        R_local_im_3_address1,
        R_local_im_3_ce1,
        R_local_im_3_q1,
        R_local_im_4_address0,
        R_local_im_4_ce0,
        R_local_im_4_q0,
        R_local_im_4_address1,
        R_local_im_4_ce1,
        R_local_im_4_q1,
        R_local_im_5_address0,
        R_local_im_5_ce0,
        R_local_im_5_q0,
        R_local_im_5_address1,
        R_local_im_5_ce1,
        R_local_im_5_q1,
        R_local_im_6_address0,
        R_local_im_6_ce0,
        R_local_im_6_q0,
        R_local_im_6_address1,
        R_local_im_6_ce1,
        R_local_im_6_q1,
        R_local_im_7_address0,
        R_local_im_7_ce0,
        R_local_im_7_q0,
        R_local_im_7_address1,
        R_local_im_7_ce1,
        R_local_im_7_q1,
        R_fb_im_7_address0,
        R_fb_im_7_ce0,
        R_fb_im_7_we0,
        R_fb_im_7_d0,
        R_fb_im_6_address0,
        R_fb_im_6_ce0,
        R_fb_im_6_we0,
        R_fb_im_6_d0,
        R_fb_im_5_address0,
        R_fb_im_5_ce0,
        R_fb_im_5_we0,
        R_fb_im_5_d0,
        R_fb_im_4_address0,
        R_fb_im_4_ce0,
        R_fb_im_4_we0,
        R_fb_im_4_d0,
        R_fb_im_3_address0,
        R_fb_im_3_ce0,
        R_fb_im_3_we0,
        R_fb_im_3_d0,
        R_fb_im_2_address0,
        R_fb_im_2_ce0,
        R_fb_im_2_we0,
        R_fb_im_2_d0,
        R_fb_im_1_address0,
        R_fb_im_1_ce0,
        R_fb_im_1_we0,
        R_fb_im_1_d0,
        R_fb_re_7_address0,
        R_fb_re_7_ce0,
        R_fb_re_7_we0,
        R_fb_re_7_d0,
        R_fb_re_6_address0,
        R_fb_re_6_ce0,
        R_fb_re_6_we0,
        R_fb_re_6_d0,
        R_fb_re_5_address0,
        R_fb_re_5_ce0,
        R_fb_re_5_we0,
        R_fb_re_5_d0,
        R_fb_re_4_address0,
        R_fb_re_4_ce0,
        R_fb_re_4_we0,
        R_fb_re_4_d0,
        R_fb_re_3_address0,
        R_fb_re_3_ce0,
        R_fb_re_3_we0,
        R_fb_re_3_d0,
        R_fb_re_2_address0,
        R_fb_re_2_ce0,
        R_fb_re_2_we0,
        R_fb_re_2_d0,
        R_fb_re_1_address0,
        R_fb_re_1_ce0,
        R_fb_re_1_we0,
        R_fb_re_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] R_fb_re_address0;
output   R_fb_re_ce0;
output   R_fb_re_we0;
output  [62:0] R_fb_re_d0;
output  [2:0] R_fb_im_address0;
output   R_fb_im_ce0;
output   R_fb_im_we0;
output  [62:0] R_fb_im_d0;
output  [2:0] R_local_re_address0;
output   R_local_re_ce0;
input  [63:0] R_local_re_q0;
output  [2:0] R_local_re_address1;
output   R_local_re_ce1;
input  [63:0] R_local_re_q1;
output  [2:0] R_local_re_1_address0;
output   R_local_re_1_ce0;
input  [63:0] R_local_re_1_q0;
output  [2:0] R_local_re_1_address1;
output   R_local_re_1_ce1;
input  [63:0] R_local_re_1_q1;
output  [2:0] R_local_re_2_address0;
output   R_local_re_2_ce0;
input  [63:0] R_local_re_2_q0;
output  [2:0] R_local_re_2_address1;
output   R_local_re_2_ce1;
input  [63:0] R_local_re_2_q1;
output  [2:0] R_local_re_3_address0;
output   R_local_re_3_ce0;
input  [63:0] R_local_re_3_q0;
output  [2:0] R_local_re_3_address1;
output   R_local_re_3_ce1;
input  [63:0] R_local_re_3_q1;
output  [2:0] R_local_re_4_address0;
output   R_local_re_4_ce0;
input  [63:0] R_local_re_4_q0;
output  [2:0] R_local_re_4_address1;
output   R_local_re_4_ce1;
input  [63:0] R_local_re_4_q1;
output  [2:0] R_local_re_5_address0;
output   R_local_re_5_ce0;
input  [63:0] R_local_re_5_q0;
output  [2:0] R_local_re_5_address1;
output   R_local_re_5_ce1;
input  [63:0] R_local_re_5_q1;
output  [2:0] R_local_re_6_address0;
output   R_local_re_6_ce0;
input  [63:0] R_local_re_6_q0;
output  [2:0] R_local_re_6_address1;
output   R_local_re_6_ce1;
input  [63:0] R_local_re_6_q1;
output  [2:0] R_local_re_7_address0;
output   R_local_re_7_ce0;
input  [63:0] R_local_re_7_q0;
output  [2:0] R_local_re_7_address1;
output   R_local_re_7_ce1;
input  [63:0] R_local_re_7_q1;
output  [2:0] R_local_im_address0;
output   R_local_im_ce0;
input  [63:0] R_local_im_q0;
output  [2:0] R_local_im_address1;
output   R_local_im_ce1;
input  [63:0] R_local_im_q1;
output  [2:0] R_local_im_1_address0;
output   R_local_im_1_ce0;
input  [63:0] R_local_im_1_q0;
output  [2:0] R_local_im_1_address1;
output   R_local_im_1_ce1;
input  [63:0] R_local_im_1_q1;
output  [2:0] R_local_im_2_address0;
output   R_local_im_2_ce0;
input  [63:0] R_local_im_2_q0;
output  [2:0] R_local_im_2_address1;
output   R_local_im_2_ce1;
input  [63:0] R_local_im_2_q1;
output  [2:0] R_local_im_3_address0;
output   R_local_im_3_ce0;
input  [63:0] R_local_im_3_q0;
output  [2:0] R_local_im_3_address1;
output   R_local_im_3_ce1;
input  [63:0] R_local_im_3_q1;
output  [2:0] R_local_im_4_address0;
output   R_local_im_4_ce0;
input  [63:0] R_local_im_4_q0;
output  [2:0] R_local_im_4_address1;
output   R_local_im_4_ce1;
input  [63:0] R_local_im_4_q1;
output  [2:0] R_local_im_5_address0;
output   R_local_im_5_ce0;
input  [63:0] R_local_im_5_q0;
output  [2:0] R_local_im_5_address1;
output   R_local_im_5_ce1;
input  [63:0] R_local_im_5_q1;
output  [2:0] R_local_im_6_address0;
output   R_local_im_6_ce0;
input  [63:0] R_local_im_6_q0;
output  [2:0] R_local_im_6_address1;
output   R_local_im_6_ce1;
input  [63:0] R_local_im_6_q1;
output  [2:0] R_local_im_7_address0;
output   R_local_im_7_ce0;
input  [63:0] R_local_im_7_q0;
output  [2:0] R_local_im_7_address1;
output   R_local_im_7_ce1;
input  [63:0] R_local_im_7_q1;
output  [2:0] R_fb_im_7_address0;
output   R_fb_im_7_ce0;
output   R_fb_im_7_we0;
output  [62:0] R_fb_im_7_d0;
output  [2:0] R_fb_im_6_address0;
output   R_fb_im_6_ce0;
output   R_fb_im_6_we0;
output  [62:0] R_fb_im_6_d0;
output  [2:0] R_fb_im_5_address0;
output   R_fb_im_5_ce0;
output   R_fb_im_5_we0;
output  [62:0] R_fb_im_5_d0;
output  [2:0] R_fb_im_4_address0;
output   R_fb_im_4_ce0;
output   R_fb_im_4_we0;
output  [62:0] R_fb_im_4_d0;
output  [2:0] R_fb_im_3_address0;
output   R_fb_im_3_ce0;
output   R_fb_im_3_we0;
output  [62:0] R_fb_im_3_d0;
output  [2:0] R_fb_im_2_address0;
output   R_fb_im_2_ce0;
output   R_fb_im_2_we0;
output  [62:0] R_fb_im_2_d0;
output  [2:0] R_fb_im_1_address0;
output   R_fb_im_1_ce0;
output   R_fb_im_1_we0;
output  [62:0] R_fb_im_1_d0;
output  [2:0] R_fb_re_7_address0;
output   R_fb_re_7_ce0;
output   R_fb_re_7_we0;
output  [62:0] R_fb_re_7_d0;
output  [2:0] R_fb_re_6_address0;
output   R_fb_re_6_ce0;
output   R_fb_re_6_we0;
output  [62:0] R_fb_re_6_d0;
output  [2:0] R_fb_re_5_address0;
output   R_fb_re_5_ce0;
output   R_fb_re_5_we0;
output  [62:0] R_fb_re_5_d0;
output  [2:0] R_fb_re_4_address0;
output   R_fb_re_4_ce0;
output   R_fb_re_4_we0;
output  [62:0] R_fb_re_4_d0;
output  [2:0] R_fb_re_3_address0;
output   R_fb_re_3_ce0;
output   R_fb_re_3_we0;
output  [62:0] R_fb_re_3_d0;
output  [2:0] R_fb_re_2_address0;
output   R_fb_re_2_ce0;
output   R_fb_re_2_we0;
output  [62:0] R_fb_re_2_d0;
output  [2:0] R_fb_re_1_address0;
output   R_fb_re_1_ce0;
output   R_fb_re_1_we0;
output  [62:0] R_fb_re_1_d0;

reg ap_idle;
reg R_fb_re_ce0;
reg R_fb_re_we0;
reg R_fb_im_ce0;
reg R_fb_im_we0;
reg R_local_re_ce0;
reg R_local_re_ce1;
reg R_local_re_1_ce0;
reg R_local_re_1_ce1;
reg R_local_re_2_ce0;
reg R_local_re_2_ce1;
reg R_local_re_3_ce0;
reg R_local_re_3_ce1;
reg R_local_re_4_ce0;
reg R_local_re_4_ce1;
reg R_local_re_5_ce0;
reg R_local_re_5_ce1;
reg R_local_re_6_ce0;
reg R_local_re_6_ce1;
reg R_local_re_7_ce0;
reg R_local_re_7_ce1;
reg R_local_im_ce0;
reg R_local_im_ce1;
reg R_local_im_1_ce0;
reg R_local_im_1_ce1;
reg R_local_im_2_ce0;
reg R_local_im_2_ce1;
reg R_local_im_3_ce0;
reg R_local_im_3_ce1;
reg R_local_im_4_ce0;
reg R_local_im_4_ce1;
reg R_local_im_5_ce0;
reg R_local_im_5_ce1;
reg R_local_im_6_ce0;
reg R_local_im_6_ce1;
reg R_local_im_7_ce0;
reg R_local_im_7_ce1;
reg R_fb_im_7_ce0;
reg R_fb_im_7_we0;
reg R_fb_im_6_ce0;
reg R_fb_im_6_we0;
reg R_fb_im_5_ce0;
reg R_fb_im_5_we0;
reg R_fb_im_4_ce0;
reg R_fb_im_4_we0;
reg R_fb_im_3_ce0;
reg R_fb_im_3_we0;
reg R_fb_im_2_ce0;
reg R_fb_im_2_we0;
reg R_fb_im_1_ce0;
reg R_fb_im_1_we0;
reg R_fb_re_7_ce0;
reg R_fb_re_7_we0;
reg R_fb_re_6_ce0;
reg R_fb_re_6_we0;
reg R_fb_re_5_ce0;
reg R_fb_re_5_we0;
reg R_fb_re_4_ce0;
reg R_fb_re_4_we0;
reg R_fb_re_3_ce0;
reg R_fb_re_3_we0;
reg R_fb_re_2_ce0;
reg R_fb_re_2_we0;
reg R_fb_re_1_ce0;
reg R_fb_re_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln71_fu_756_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln71_fu_802_p1;
reg   [63:0] zext_ln71_reg_1052;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln75_fu_864_p1;
reg   [2:0] trunc_ln75_reg_1232;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln71_1_fu_844_p1;
reg   [3:0] j_fu_118;
wire   [3:0] add_ln72_fu_868_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [3:0] i_1_fu_122;
wire   [3:0] select_ln71_1_fu_794_p3;
reg   [3:0] ap_sig_allocacmp_i_1_load;
reg   [6:0] indvar_flatten_fu_126;
wire   [6:0] add_ln71_fu_762_p2;
reg   [6:0] ap_sig_allocacmp_indvar_flatten_load;
wire   [0:0] icmp_ln72_fu_774_p2;
wire   [3:0] add_ln71_1_fu_788_p2;
wire   [2:0] trunc_ln71_fu_822_p1;
wire   [2:0] trunc_ln71_1_fu_826_p1;
wire   [2:0] select_ln71_2_fu_830_p3;
wire   [2:0] xor_ln71_fu_838_p2;
wire   [3:0] select_ln71_fu_780_p3;
wire   [2:0] xor_ln78_fu_931_p2;
wire   [63:0] val_swap_fu_936_p10;
wire   [63:0] val_re_fu_889_p10;
wire   [63:0] add_ln81_fu_980_p2;
wire   [63:0] val_im_fu_910_p10;
wire   [63:0] tmp_fu_958_p10;
wire   [63:0] sub_ln82_fu_1004_p2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

real_converter_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U18(
    .din0(R_local_re_q1),
    .din1(R_local_re_1_q1),
    .din2(R_local_re_2_q1),
    .din3(R_local_re_3_q1),
    .din4(R_local_re_4_q1),
    .din5(R_local_re_5_q1),
    .din6(R_local_re_6_q1),
    .din7(R_local_re_7_q1),
    .din8(trunc_ln75_reg_1232),
    .dout(val_re_fu_889_p10)
);

real_converter_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U19(
    .din0(R_local_im_q1),
    .din1(R_local_im_1_q1),
    .din2(R_local_im_2_q1),
    .din3(R_local_im_3_q1),
    .din4(R_local_im_4_q1),
    .din5(R_local_im_5_q1),
    .din6(R_local_im_6_q1),
    .din7(R_local_im_7_q1),
    .din8(trunc_ln75_reg_1232),
    .dout(val_im_fu_910_p10)
);

real_converter_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U20(
    .din0(R_local_re_q0),
    .din1(R_local_re_1_q0),
    .din2(R_local_re_2_q0),
    .din3(R_local_re_3_q0),
    .din4(R_local_re_4_q0),
    .din5(R_local_re_5_q0),
    .din6(R_local_re_6_q0),
    .din7(R_local_re_7_q0),
    .din8(xor_ln78_fu_931_p2),
    .dout(val_swap_fu_936_p10)
);

real_converter_mux_83_64_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 64 ),
    .din1_WIDTH( 64 ),
    .din2_WIDTH( 64 ),
    .din3_WIDTH( 64 ),
    .din4_WIDTH( 64 ),
    .din5_WIDTH( 64 ),
    .din6_WIDTH( 64 ),
    .din7_WIDTH( 64 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 64 ))
mux_83_64_1_1_U21(
    .din0(R_local_im_q0),
    .din1(R_local_im_1_q0),
    .din2(R_local_im_2_q0),
    .din3(R_local_im_3_q0),
    .din4(R_local_im_4_q0),
    .din5(R_local_im_5_q0),
    .din6(R_local_im_6_q0),
    .din7(R_local_im_7_q0),
    .din8(xor_ln78_fu_931_p2),
    .dout(tmp_fu_958_p10)
);

real_converter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln71_fu_756_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_1_fu_122 <= select_ln71_1_fu_794_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_1_fu_122 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln71_fu_756_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten_fu_126 <= add_ln71_fu_762_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten_fu_126 <= 7'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln71_fu_756_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_118 <= add_ln72_fu_868_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_118 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln71_fu_756_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln75_reg_1232 <= trunc_ln75_fu_864_p1;
        zext_ln71_reg_1052[3 : 0] <= zext_ln71_fu_802_p1[3 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_1_ce0 = 1'b1;
    end else begin
        R_fb_im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_1_we0 = 1'b1;
    end else begin
        R_fb_im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_2_ce0 = 1'b1;
    end else begin
        R_fb_im_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_2_we0 = 1'b1;
    end else begin
        R_fb_im_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_3_ce0 = 1'b1;
    end else begin
        R_fb_im_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_3_we0 = 1'b1;
    end else begin
        R_fb_im_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_4_ce0 = 1'b1;
    end else begin
        R_fb_im_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_4_we0 = 1'b1;
    end else begin
        R_fb_im_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_5_ce0 = 1'b1;
    end else begin
        R_fb_im_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_5_we0 = 1'b1;
    end else begin
        R_fb_im_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_6_ce0 = 1'b1;
    end else begin
        R_fb_im_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_6_we0 = 1'b1;
    end else begin
        R_fb_im_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_7_ce0 = 1'b1;
    end else begin
        R_fb_im_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_7_we0 = 1'b1;
    end else begin
        R_fb_im_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_ce0 = 1'b1;
    end else begin
        R_fb_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_we0 = 1'b1;
    end else begin
        R_fb_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_1_ce0 = 1'b1;
    end else begin
        R_fb_re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd1) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_1_we0 = 1'b1;
    end else begin
        R_fb_re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_2_ce0 = 1'b1;
    end else begin
        R_fb_re_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd2) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_2_we0 = 1'b1;
    end else begin
        R_fb_re_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_3_ce0 = 1'b1;
    end else begin
        R_fb_re_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd3) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_3_we0 = 1'b1;
    end else begin
        R_fb_re_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_4_ce0 = 1'b1;
    end else begin
        R_fb_re_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd4) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_4_we0 = 1'b1;
    end else begin
        R_fb_re_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_5_ce0 = 1'b1;
    end else begin
        R_fb_re_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd5) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_5_we0 = 1'b1;
    end else begin
        R_fb_re_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_6_ce0 = 1'b1;
    end else begin
        R_fb_re_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd6) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_6_we0 = 1'b1;
    end else begin
        R_fb_re_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_7_ce0 = 1'b1;
    end else begin
        R_fb_re_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd7) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_7_we0 = 1'b1;
    end else begin
        R_fb_re_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_ce0 = 1'b1;
    end else begin
        R_fb_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((trunc_ln75_reg_1232 == 3'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_we0 = 1'b1;
    end else begin
        R_fb_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_1_ce0 = 1'b1;
    end else begin
        R_local_im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_1_ce1 = 1'b1;
    end else begin
        R_local_im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_2_ce0 = 1'b1;
    end else begin
        R_local_im_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_2_ce1 = 1'b1;
    end else begin
        R_local_im_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_3_ce0 = 1'b1;
    end else begin
        R_local_im_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_3_ce1 = 1'b1;
    end else begin
        R_local_im_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_4_ce0 = 1'b1;
    end else begin
        R_local_im_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_4_ce1 = 1'b1;
    end else begin
        R_local_im_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_5_ce0 = 1'b1;
    end else begin
        R_local_im_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_5_ce1 = 1'b1;
    end else begin
        R_local_im_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_6_ce0 = 1'b1;
    end else begin
        R_local_im_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_6_ce1 = 1'b1;
    end else begin
        R_local_im_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_7_ce0 = 1'b1;
    end else begin
        R_local_im_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_7_ce1 = 1'b1;
    end else begin
        R_local_im_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_ce0 = 1'b1;
    end else begin
        R_local_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_im_ce1 = 1'b1;
    end else begin
        R_local_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_1_ce0 = 1'b1;
    end else begin
        R_local_re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_1_ce1 = 1'b1;
    end else begin
        R_local_re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_2_ce0 = 1'b1;
    end else begin
        R_local_re_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_2_ce1 = 1'b1;
    end else begin
        R_local_re_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_3_ce0 = 1'b1;
    end else begin
        R_local_re_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_3_ce1 = 1'b1;
    end else begin
        R_local_re_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_4_ce0 = 1'b1;
    end else begin
        R_local_re_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_4_ce1 = 1'b1;
    end else begin
        R_local_re_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_5_ce0 = 1'b1;
    end else begin
        R_local_re_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_5_ce1 = 1'b1;
    end else begin
        R_local_re_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_6_ce0 = 1'b1;
    end else begin
        R_local_re_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_6_ce1 = 1'b1;
    end else begin
        R_local_re_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_7_ce0 = 1'b1;
    end else begin
        R_local_re_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_7_ce1 = 1'b1;
    end else begin
        R_local_re_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_ce0 = 1'b1;
    end else begin
        R_local_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_local_re_ce1 = 1'b1;
    end else begin
        R_local_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln71_fu_756_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_1_load = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1_load = i_1_fu_122;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten_load = 7'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten_load = indvar_flatten_fu_126;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_118;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_fb_im_1_address0 = zext_ln71_reg_1052;

assign R_fb_im_1_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_im_2_address0 = zext_ln71_reg_1052;

assign R_fb_im_2_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_im_3_address0 = zext_ln71_reg_1052;

assign R_fb_im_3_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_im_4_address0 = zext_ln71_reg_1052;

assign R_fb_im_4_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_im_5_address0 = zext_ln71_reg_1052;

assign R_fb_im_5_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_im_6_address0 = zext_ln71_reg_1052;

assign R_fb_im_6_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_im_7_address0 = zext_ln71_reg_1052;

assign R_fb_im_7_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_im_address0 = zext_ln71_reg_1052;

assign R_fb_im_d0 = {{sub_ln82_fu_1004_p2[63:1]}};

assign R_fb_re_1_address0 = zext_ln71_reg_1052;

assign R_fb_re_1_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_fb_re_2_address0 = zext_ln71_reg_1052;

assign R_fb_re_2_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_fb_re_3_address0 = zext_ln71_reg_1052;

assign R_fb_re_3_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_fb_re_4_address0 = zext_ln71_reg_1052;

assign R_fb_re_4_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_fb_re_5_address0 = zext_ln71_reg_1052;

assign R_fb_re_5_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_fb_re_6_address0 = zext_ln71_reg_1052;

assign R_fb_re_6_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_fb_re_7_address0 = zext_ln71_reg_1052;

assign R_fb_re_7_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_fb_re_address0 = zext_ln71_reg_1052;

assign R_fb_re_d0 = {{add_ln81_fu_980_p2[63:1]}};

assign R_local_im_1_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_1_address1 = zext_ln71_fu_802_p1;

assign R_local_im_2_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_2_address1 = zext_ln71_fu_802_p1;

assign R_local_im_3_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_3_address1 = zext_ln71_fu_802_p1;

assign R_local_im_4_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_4_address1 = zext_ln71_fu_802_p1;

assign R_local_im_5_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_5_address1 = zext_ln71_fu_802_p1;

assign R_local_im_6_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_6_address1 = zext_ln71_fu_802_p1;

assign R_local_im_7_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_7_address1 = zext_ln71_fu_802_p1;

assign R_local_im_address0 = zext_ln71_1_fu_844_p1;

assign R_local_im_address1 = zext_ln71_fu_802_p1;

assign R_local_re_1_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_1_address1 = zext_ln71_fu_802_p1;

assign R_local_re_2_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_2_address1 = zext_ln71_fu_802_p1;

assign R_local_re_3_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_3_address1 = zext_ln71_fu_802_p1;

assign R_local_re_4_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_4_address1 = zext_ln71_fu_802_p1;

assign R_local_re_5_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_5_address1 = zext_ln71_fu_802_p1;

assign R_local_re_6_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_6_address1 = zext_ln71_fu_802_p1;

assign R_local_re_7_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_7_address1 = zext_ln71_fu_802_p1;

assign R_local_re_address0 = zext_ln71_1_fu_844_p1;

assign R_local_re_address1 = zext_ln71_fu_802_p1;

assign add_ln71_1_fu_788_p2 = (ap_sig_allocacmp_i_1_load + 4'd1);

assign add_ln71_fu_762_p2 = (ap_sig_allocacmp_indvar_flatten_load + 7'd1);

assign add_ln72_fu_868_p2 = (select_ln71_fu_780_p3 + 4'd1);

assign add_ln81_fu_980_p2 = (val_swap_fu_936_p10 + val_re_fu_889_p10);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln71_fu_756_p2 = ((ap_sig_allocacmp_indvar_flatten_load == 7'd64) ? 1'b1 : 1'b0);

assign icmp_ln72_fu_774_p2 = ((ap_sig_allocacmp_j_load == 4'd8) ? 1'b1 : 1'b0);

assign select_ln71_1_fu_794_p3 = ((icmp_ln72_fu_774_p2[0:0] == 1'b1) ? add_ln71_1_fu_788_p2 : ap_sig_allocacmp_i_1_load);

assign select_ln71_2_fu_830_p3 = ((icmp_ln72_fu_774_p2[0:0] == 1'b1) ? trunc_ln71_fu_822_p1 : trunc_ln71_1_fu_826_p1);

assign select_ln71_fu_780_p3 = ((icmp_ln72_fu_774_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign sub_ln82_fu_1004_p2 = (val_im_fu_910_p10 - tmp_fu_958_p10);

assign trunc_ln71_1_fu_826_p1 = ap_sig_allocacmp_i_1_load[2:0];

assign trunc_ln71_fu_822_p1 = add_ln71_1_fu_788_p2[2:0];

assign trunc_ln75_fu_864_p1 = select_ln71_fu_780_p3[2:0];

assign xor_ln71_fu_838_p2 = (select_ln71_2_fu_830_p3 ^ 3'd7);

assign xor_ln78_fu_931_p2 = (trunc_ln75_reg_1232 ^ 3'd7);

assign zext_ln71_1_fu_844_p1 = xor_ln71_fu_838_p2;

assign zext_ln71_fu_802_p1 = select_ln71_1_fu_794_p3;

always @ (posedge ap_clk) begin
    zext_ln71_reg_1052[63:4] <= 60'b000000000000000000000000000000000000000000000000000000000000;
end

endmodule //real_converter_real_converter_Pipeline_FB_ROW_FB_COL
