// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module real_converter_real_converter_Pipeline_LOAD_ROW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        R_in_TVALID,
        R_local_im_7_address0,
        R_local_im_7_ce0,
        R_local_im_7_we0,
        R_local_im_7_d0,
        R_local_im_6_address0,
        R_local_im_6_ce0,
        R_local_im_6_we0,
        R_local_im_6_d0,
        R_local_im_5_address0,
        R_local_im_5_ce0,
        R_local_im_5_we0,
        R_local_im_5_d0,
        R_local_im_4_address0,
        R_local_im_4_ce0,
        R_local_im_4_we0,
        R_local_im_4_d0,
        R_local_im_3_address0,
        R_local_im_3_ce0,
        R_local_im_3_we0,
        R_local_im_3_d0,
        R_local_im_2_address0,
        R_local_im_2_ce0,
        R_local_im_2_we0,
        R_local_im_2_d0,
        R_local_im_1_address0,
        R_local_im_1_ce0,
        R_local_im_1_we0,
        R_local_im_1_d0,
        R_local_im_address0,
        R_local_im_ce0,
        R_local_im_we0,
        R_local_im_d0,
        R_local_re_7_address0,
        R_local_re_7_ce0,
        R_local_re_7_we0,
        R_local_re_7_d0,
        R_local_re_6_address0,
        R_local_re_6_ce0,
        R_local_re_6_we0,
        R_local_re_6_d0,
        R_local_re_5_address0,
        R_local_re_5_ce0,
        R_local_re_5_we0,
        R_local_re_5_d0,
        R_local_re_4_address0,
        R_local_re_4_ce0,
        R_local_re_4_we0,
        R_local_re_4_d0,
        R_local_re_3_address0,
        R_local_re_3_ce0,
        R_local_re_3_we0,
        R_local_re_3_d0,
        R_local_re_2_address0,
        R_local_re_2_ce0,
        R_local_re_2_we0,
        R_local_re_2_d0,
        R_local_re_1_address0,
        R_local_re_1_ce0,
        R_local_re_1_we0,
        R_local_re_1_d0,
        R_local_re_address0,
        R_local_re_ce0,
        R_local_re_we0,
        R_local_re_d0,
        R_in_TDATA,
        R_in_TREADY
);

parameter    ap_ST_fsm_state1 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   R_in_TVALID;
output  [2:0] R_local_im_7_address0;
output   R_local_im_7_ce0;
output   R_local_im_7_we0;
output  [63:0] R_local_im_7_d0;
output  [2:0] R_local_im_6_address0;
output   R_local_im_6_ce0;
output   R_local_im_6_we0;
output  [63:0] R_local_im_6_d0;
output  [2:0] R_local_im_5_address0;
output   R_local_im_5_ce0;
output   R_local_im_5_we0;
output  [63:0] R_local_im_5_d0;
output  [2:0] R_local_im_4_address0;
output   R_local_im_4_ce0;
output   R_local_im_4_we0;
output  [63:0] R_local_im_4_d0;
output  [2:0] R_local_im_3_address0;
output   R_local_im_3_ce0;
output   R_local_im_3_we0;
output  [63:0] R_local_im_3_d0;
output  [2:0] R_local_im_2_address0;
output   R_local_im_2_ce0;
output   R_local_im_2_we0;
output  [63:0] R_local_im_2_d0;
output  [2:0] R_local_im_1_address0;
output   R_local_im_1_ce0;
output   R_local_im_1_we0;
output  [63:0] R_local_im_1_d0;
output  [2:0] R_local_im_address0;
output   R_local_im_ce0;
output   R_local_im_we0;
output  [63:0] R_local_im_d0;
output  [2:0] R_local_re_7_address0;
output   R_local_re_7_ce0;
output   R_local_re_7_we0;
output  [63:0] R_local_re_7_d0;
output  [2:0] R_local_re_6_address0;
output   R_local_re_6_ce0;
output   R_local_re_6_we0;
output  [63:0] R_local_re_6_d0;
output  [2:0] R_local_re_5_address0;
output   R_local_re_5_ce0;
output   R_local_re_5_we0;
output  [63:0] R_local_re_5_d0;
output  [2:0] R_local_re_4_address0;
output   R_local_re_4_ce0;
output   R_local_re_4_we0;
output  [63:0] R_local_re_4_d0;
output  [2:0] R_local_re_3_address0;
output   R_local_re_3_ce0;
output   R_local_re_3_we0;
output  [63:0] R_local_re_3_d0;
output  [2:0] R_local_re_2_address0;
output   R_local_re_2_ce0;
output   R_local_re_2_we0;
output  [63:0] R_local_re_2_d0;
output  [2:0] R_local_re_1_address0;
output   R_local_re_1_ce0;
output   R_local_re_1_we0;
output  [63:0] R_local_re_1_d0;
output  [2:0] R_local_re_address0;
output   R_local_re_ce0;
output   R_local_re_we0;
output  [63:0] R_local_re_d0;
input  [1023:0] R_in_TDATA;
output   R_in_TREADY;

reg ap_idle;
reg R_local_im_7_ce0;
reg R_local_im_7_we0;
reg R_local_im_6_ce0;
reg R_local_im_6_we0;
reg R_local_im_5_ce0;
reg R_local_im_5_we0;
reg R_local_im_4_ce0;
reg R_local_im_4_we0;
reg R_local_im_3_ce0;
reg R_local_im_3_we0;
reg R_local_im_2_ce0;
reg R_local_im_2_we0;
reg R_local_im_1_ce0;
reg R_local_im_1_we0;
reg R_local_im_ce0;
reg R_local_im_we0;
reg R_local_re_7_ce0;
reg R_local_re_7_we0;
reg R_local_re_6_ce0;
reg R_local_re_6_we0;
reg R_local_re_5_ce0;
reg R_local_re_5_we0;
reg R_local_re_4_ce0;
reg R_local_re_4_we0;
reg R_local_re_3_ce0;
reg R_local_re_3_we0;
reg R_local_re_2_ce0;
reg R_local_re_2_we0;
reg R_local_re_1_ce0;
reg R_local_re_1_we0;
reg R_local_re_ce0;
reg R_local_re_we0;
reg R_in_TREADY;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_state1;
wire   [0:0] icmp_ln56_fu_356_p2;
reg    ap_block_state1_pp0_stage0_iter0;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    R_in_TDATA_blk_n;
wire   [63:0] zext_ln56_fu_368_p1;
reg   [3:0] i_fu_130;
wire   [3:0] add_ln56_fu_362_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_2;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
reg    ap_ST_fsm_state1_blk;
wire    ap_start_int;
reg    ap_condition_327;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_done_reg = 1'b0;
end

real_converter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_state1;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if ((1'b1 == ap_condition_327)) begin
        if ((icmp_ln56_fu_356_p2 == 1'd0)) begin
            i_fu_130 <= add_ln56_fu_362_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_130 <= 4'd0;
        end
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b1) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_in_TDATA_blk_n = R_in_TVALID;
    end else begin
        R_in_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_in_TREADY = 1'b1;
    end else begin
        R_in_TREADY = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_1_ce0 = 1'b1;
    end else begin
        R_local_im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_1_we0 = 1'b1;
    end else begin
        R_local_im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_2_ce0 = 1'b1;
    end else begin
        R_local_im_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_2_we0 = 1'b1;
    end else begin
        R_local_im_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_3_ce0 = 1'b1;
    end else begin
        R_local_im_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_3_we0 = 1'b1;
    end else begin
        R_local_im_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_4_ce0 = 1'b1;
    end else begin
        R_local_im_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_4_we0 = 1'b1;
    end else begin
        R_local_im_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_5_ce0 = 1'b1;
    end else begin
        R_local_im_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_5_we0 = 1'b1;
    end else begin
        R_local_im_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_6_ce0 = 1'b1;
    end else begin
        R_local_im_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_6_we0 = 1'b1;
    end else begin
        R_local_im_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_7_ce0 = 1'b1;
    end else begin
        R_local_im_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_7_we0 = 1'b1;
    end else begin
        R_local_im_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_ce0 = 1'b1;
    end else begin
        R_local_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_im_we0 = 1'b1;
    end else begin
        R_local_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_1_ce0 = 1'b1;
    end else begin
        R_local_re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_1_we0 = 1'b1;
    end else begin
        R_local_re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_2_ce0 = 1'b1;
    end else begin
        R_local_re_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_2_we0 = 1'b1;
    end else begin
        R_local_re_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_3_ce0 = 1'b1;
    end else begin
        R_local_re_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_3_we0 = 1'b1;
    end else begin
        R_local_re_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_4_ce0 = 1'b1;
    end else begin
        R_local_re_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_4_we0 = 1'b1;
    end else begin
        R_local_re_4_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_5_ce0 = 1'b1;
    end else begin
        R_local_re_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_5_we0 = 1'b1;
    end else begin
        R_local_re_5_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_6_ce0 = 1'b1;
    end else begin
        R_local_re_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_6_we0 = 1'b1;
    end else begin
        R_local_re_6_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_7_ce0 = 1'b1;
    end else begin
        R_local_re_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_7_we0 = 1'b1;
    end else begin
        R_local_re_7_we0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_ce0 = 1'b1;
    end else begin
        R_local_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd0) & (1'b1 == ap_CS_fsm_state1))) begin
        R_local_re_we0 = 1'b1;
    end else begin
        R_local_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0)))) begin
        ap_ST_fsm_state1_blk = 1'b1;
    end else begin
        ap_ST_fsm_state1_blk = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (icmp_ln56_fu_356_p2 == 1'd1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (ap_loop_exit_ready == 1'b1) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if ((~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b1 == ap_CS_fsm_state1) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_2 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_2 = i_fu_130;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_state1 : begin
            ap_NS_fsm = ap_ST_fsm_state1;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_local_im_1_address0 = zext_ln56_fu_368_p1;

assign R_local_im_1_d0 = {{R_in_TDATA[255:192]}};

assign R_local_im_2_address0 = zext_ln56_fu_368_p1;

assign R_local_im_2_d0 = {{R_in_TDATA[383:320]}};

assign R_local_im_3_address0 = zext_ln56_fu_368_p1;

assign R_local_im_3_d0 = {{R_in_TDATA[511:448]}};

assign R_local_im_4_address0 = zext_ln56_fu_368_p1;

assign R_local_im_4_d0 = {{R_in_TDATA[639:576]}};

assign R_local_im_5_address0 = zext_ln56_fu_368_p1;

assign R_local_im_5_d0 = {{R_in_TDATA[767:704]}};

assign R_local_im_6_address0 = zext_ln56_fu_368_p1;

assign R_local_im_6_d0 = {{R_in_TDATA[895:832]}};

assign R_local_im_7_address0 = zext_ln56_fu_368_p1;

assign R_local_im_7_d0 = {{R_in_TDATA[1023:960]}};

assign R_local_im_address0 = zext_ln56_fu_368_p1;

assign R_local_im_d0 = {{R_in_TDATA[127:64]}};

assign R_local_re_1_address0 = zext_ln56_fu_368_p1;

assign R_local_re_1_d0 = {{R_in_TDATA[191:128]}};

assign R_local_re_2_address0 = zext_ln56_fu_368_p1;

assign R_local_re_2_d0 = {{R_in_TDATA[319:256]}};

assign R_local_re_3_address0 = zext_ln56_fu_368_p1;

assign R_local_re_3_d0 = {{R_in_TDATA[447:384]}};

assign R_local_re_4_address0 = zext_ln56_fu_368_p1;

assign R_local_re_4_d0 = {{R_in_TDATA[575:512]}};

assign R_local_re_5_address0 = zext_ln56_fu_368_p1;

assign R_local_re_5_d0 = {{R_in_TDATA[703:640]}};

assign R_local_re_6_address0 = zext_ln56_fu_368_p1;

assign R_local_re_6_d0 = {{R_in_TDATA[831:768]}};

assign R_local_re_7_address0 = zext_ln56_fu_368_p1;

assign R_local_re_7_d0 = {{R_in_TDATA[959:896]}};

assign R_local_re_address0 = zext_ln56_fu_368_p1;

assign R_local_re_d0 = R_in_TDATA[63:0];

assign add_ln56_fu_362_p2 = (ap_sig_allocacmp_i_2 + 4'd1);

assign ap_CS_fsm_state1 = ap_CS_fsm[32'd0];

always @ (*) begin
    ap_block_state1_pp0_stage0_iter0 = ((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0)));
end

always @ (*) begin
    ap_condition_327 = (~((ap_start_int == 1'b0) | ((1'b0 == R_in_TVALID) & (icmp_ln56_fu_356_p2 == 1'd0))) & (1'b1 == ap_CS_fsm_state1));
end

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln56_fu_356_p2 = ((ap_sig_allocacmp_i_2 == 4'd8) ? 1'b1 : 1'b0);

assign zext_ln56_fu_368_p1 = ap_sig_allocacmp_i_2;

endmodule //real_converter_real_converter_Pipeline_LOAD_ROW
