// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module real_converter_real_converter_Pipeline_Q1_ROW_Q1_COL (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        Tmp_re_address0,
        Tmp_re_ce0,
        Tmp_re_we0,
        Tmp_re_d0,
        R_fb_re_address0,
        R_fb_re_ce0,
        R_fb_re_q0,
        R_fb_re_address1,
        R_fb_re_ce1,
        R_fb_re_q1,
        R_fb_re_1_address0,
        R_fb_re_1_ce0,
        R_fb_re_1_q0,
        R_fb_re_1_address1,
        R_fb_re_1_ce1,
        R_fb_re_1_q1,
        R_fb_re_2_address0,
        R_fb_re_2_ce0,
        R_fb_re_2_q0,
        R_fb_re_2_address1,
        R_fb_re_2_ce1,
        R_fb_re_2_q1,
        R_fb_re_3_address0,
        R_fb_re_3_ce0,
        R_fb_re_3_q0,
        R_fb_re_3_address1,
        R_fb_re_3_ce1,
        R_fb_re_3_q1,
        R_fb_re_4_address0,
        R_fb_re_4_ce0,
        R_fb_re_4_q0,
        R_fb_re_4_address1,
        R_fb_re_4_ce1,
        R_fb_re_4_q1,
        R_fb_re_5_address0,
        R_fb_re_5_ce0,
        R_fb_re_5_q0,
        R_fb_re_5_address1,
        R_fb_re_5_ce1,
        R_fb_re_5_q1,
        R_fb_re_6_address0,
        R_fb_re_6_ce0,
        R_fb_re_6_q0,
        R_fb_re_6_address1,
        R_fb_re_6_ce1,
        R_fb_re_6_q1,
        R_fb_re_7_address0,
        R_fb_re_7_ce0,
        R_fb_re_7_q0,
        R_fb_re_7_address1,
        R_fb_re_7_ce1,
        R_fb_re_7_q1,
        R_fb_im_address0,
        R_fb_im_ce0,
        R_fb_im_q0,
        R_fb_im_address1,
        R_fb_im_ce1,
        R_fb_im_q1,
        R_fb_im_1_address0,
        R_fb_im_1_ce0,
        R_fb_im_1_q0,
        R_fb_im_1_address1,
        R_fb_im_1_ce1,
        R_fb_im_1_q1,
        R_fb_im_2_address0,
        R_fb_im_2_ce0,
        R_fb_im_2_q0,
        R_fb_im_2_address1,
        R_fb_im_2_ce1,
        R_fb_im_2_q1,
        R_fb_im_3_address0,
        R_fb_im_3_ce0,
        R_fb_im_3_q0,
        R_fb_im_3_address1,
        R_fb_im_3_ce1,
        R_fb_im_3_q1,
        R_fb_im_4_address0,
        R_fb_im_4_ce0,
        R_fb_im_4_q0,
        R_fb_im_4_address1,
        R_fb_im_4_ce1,
        R_fb_im_4_q1,
        R_fb_im_5_address0,
        R_fb_im_5_ce0,
        R_fb_im_5_q0,
        R_fb_im_5_address1,
        R_fb_im_5_ce1,
        R_fb_im_5_q1,
        R_fb_im_6_address0,
        R_fb_im_6_ce0,
        R_fb_im_6_q0,
        R_fb_im_6_address1,
        R_fb_im_6_ce1,
        R_fb_im_6_q1,
        R_fb_im_7_address0,
        R_fb_im_7_ce0,
        R_fb_im_7_q0,
        R_fb_im_7_address1,
        R_fb_im_7_ce1,
        R_fb_im_7_q1,
        Tmp_im_3_address0,
        Tmp_im_3_ce0,
        Tmp_im_3_we0,
        Tmp_im_3_d0,
        Tmp_im_2_address0,
        Tmp_im_2_ce0,
        Tmp_im_2_we0,
        Tmp_im_2_d0,
        Tmp_im_1_address0,
        Tmp_im_1_ce0,
        Tmp_im_1_we0,
        Tmp_im_1_d0,
        Tmp_im_address0,
        Tmp_im_ce0,
        Tmp_im_we0,
        Tmp_im_d0,
        Tmp_re_3_address0,
        Tmp_re_3_ce0,
        Tmp_re_3_we0,
        Tmp_re_3_d0,
        Tmp_re_2_address0,
        Tmp_re_2_ce0,
        Tmp_re_2_we0,
        Tmp_re_2_d0,
        Tmp_re_1_address0,
        Tmp_re_1_ce0,
        Tmp_re_1_we0,
        Tmp_re_1_d0
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
output  [2:0] Tmp_re_address0;
output   Tmp_re_ce0;
output   Tmp_re_we0;
output  [63:0] Tmp_re_d0;
output  [2:0] R_fb_re_address0;
output   R_fb_re_ce0;
input  [62:0] R_fb_re_q0;
output  [2:0] R_fb_re_address1;
output   R_fb_re_ce1;
input  [62:0] R_fb_re_q1;
output  [2:0] R_fb_re_1_address0;
output   R_fb_re_1_ce0;
input  [62:0] R_fb_re_1_q0;
output  [2:0] R_fb_re_1_address1;
output   R_fb_re_1_ce1;
input  [62:0] R_fb_re_1_q1;
output  [2:0] R_fb_re_2_address0;
output   R_fb_re_2_ce0;
input  [62:0] R_fb_re_2_q0;
output  [2:0] R_fb_re_2_address1;
output   R_fb_re_2_ce1;
input  [62:0] R_fb_re_2_q1;
output  [2:0] R_fb_re_3_address0;
output   R_fb_re_3_ce0;
input  [62:0] R_fb_re_3_q0;
output  [2:0] R_fb_re_3_address1;
output   R_fb_re_3_ce1;
input  [62:0] R_fb_re_3_q1;
output  [2:0] R_fb_re_4_address0;
output   R_fb_re_4_ce0;
input  [62:0] R_fb_re_4_q0;
output  [2:0] R_fb_re_4_address1;
output   R_fb_re_4_ce1;
input  [62:0] R_fb_re_4_q1;
output  [2:0] R_fb_re_5_address0;
output   R_fb_re_5_ce0;
input  [62:0] R_fb_re_5_q0;
output  [2:0] R_fb_re_5_address1;
output   R_fb_re_5_ce1;
input  [62:0] R_fb_re_5_q1;
output  [2:0] R_fb_re_6_address0;
output   R_fb_re_6_ce0;
input  [62:0] R_fb_re_6_q0;
output  [2:0] R_fb_re_6_address1;
output   R_fb_re_6_ce1;
input  [62:0] R_fb_re_6_q1;
output  [2:0] R_fb_re_7_address0;
output   R_fb_re_7_ce0;
input  [62:0] R_fb_re_7_q0;
output  [2:0] R_fb_re_7_address1;
output   R_fb_re_7_ce1;
input  [62:0] R_fb_re_7_q1;
output  [2:0] R_fb_im_address0;
output   R_fb_im_ce0;
input  [62:0] R_fb_im_q0;
output  [2:0] R_fb_im_address1;
output   R_fb_im_ce1;
input  [62:0] R_fb_im_q1;
output  [2:0] R_fb_im_1_address0;
output   R_fb_im_1_ce0;
input  [62:0] R_fb_im_1_q0;
output  [2:0] R_fb_im_1_address1;
output   R_fb_im_1_ce1;
input  [62:0] R_fb_im_1_q1;
output  [2:0] R_fb_im_2_address0;
output   R_fb_im_2_ce0;
input  [62:0] R_fb_im_2_q0;
output  [2:0] R_fb_im_2_address1;
output   R_fb_im_2_ce1;
input  [62:0] R_fb_im_2_q1;
output  [2:0] R_fb_im_3_address0;
output   R_fb_im_3_ce0;
input  [62:0] R_fb_im_3_q0;
output  [2:0] R_fb_im_3_address1;
output   R_fb_im_3_ce1;
input  [62:0] R_fb_im_3_q1;
output  [2:0] R_fb_im_4_address0;
output   R_fb_im_4_ce0;
input  [62:0] R_fb_im_4_q0;
output  [2:0] R_fb_im_4_address1;
output   R_fb_im_4_ce1;
input  [62:0] R_fb_im_4_q1;
output  [2:0] R_fb_im_5_address0;
output   R_fb_im_5_ce0;
input  [62:0] R_fb_im_5_q0;
output  [2:0] R_fb_im_5_address1;
output   R_fb_im_5_ce1;
input  [62:0] R_fb_im_5_q1;
output  [2:0] R_fb_im_6_address0;
output   R_fb_im_6_ce0;
input  [62:0] R_fb_im_6_q0;
output  [2:0] R_fb_im_6_address1;
output   R_fb_im_6_ce1;
input  [62:0] R_fb_im_6_q1;
output  [2:0] R_fb_im_7_address0;
output   R_fb_im_7_ce0;
input  [62:0] R_fb_im_7_q0;
output  [2:0] R_fb_im_7_address1;
output   R_fb_im_7_ce1;
input  [62:0] R_fb_im_7_q1;
output  [2:0] Tmp_im_3_address0;
output   Tmp_im_3_ce0;
output   Tmp_im_3_we0;
output  [63:0] Tmp_im_3_d0;
output  [2:0] Tmp_im_2_address0;
output   Tmp_im_2_ce0;
output   Tmp_im_2_we0;
output  [63:0] Tmp_im_2_d0;
output  [2:0] Tmp_im_1_address0;
output   Tmp_im_1_ce0;
output   Tmp_im_1_we0;
output  [63:0] Tmp_im_1_d0;
output  [2:0] Tmp_im_address0;
output   Tmp_im_ce0;
output   Tmp_im_we0;
output  [63:0] Tmp_im_d0;
output  [2:0] Tmp_re_3_address0;
output   Tmp_re_3_ce0;
output   Tmp_re_3_we0;
output  [63:0] Tmp_re_3_d0;
output  [2:0] Tmp_re_2_address0;
output   Tmp_re_2_ce0;
output   Tmp_re_2_we0;
output  [63:0] Tmp_re_2_d0;
output  [2:0] Tmp_re_1_address0;
output   Tmp_re_1_ce0;
output   Tmp_re_1_we0;
output  [63:0] Tmp_re_1_d0;

reg ap_idle;
reg Tmp_re_ce0;
reg Tmp_re_we0;
reg R_fb_re_ce0;
reg R_fb_re_ce1;
reg R_fb_re_1_ce0;
reg R_fb_re_1_ce1;
reg R_fb_re_2_ce0;
reg R_fb_re_2_ce1;
reg R_fb_re_3_ce0;
reg R_fb_re_3_ce1;
reg R_fb_re_4_ce0;
reg R_fb_re_4_ce1;
reg R_fb_re_5_ce0;
reg R_fb_re_5_ce1;
reg R_fb_re_6_ce0;
reg R_fb_re_6_ce1;
reg R_fb_re_7_ce0;
reg R_fb_re_7_ce1;
reg R_fb_im_ce0;
reg R_fb_im_ce1;
reg R_fb_im_1_ce0;
reg R_fb_im_1_ce1;
reg R_fb_im_2_ce0;
reg R_fb_im_2_ce1;
reg R_fb_im_3_ce0;
reg R_fb_im_3_ce1;
reg R_fb_im_4_ce0;
reg R_fb_im_4_ce1;
reg R_fb_im_5_ce0;
reg R_fb_im_5_ce1;
reg R_fb_im_6_ce0;
reg R_fb_im_6_ce1;
reg R_fb_im_7_ce0;
reg R_fb_im_7_ce1;
reg Tmp_im_3_ce0;
reg Tmp_im_3_we0;
reg Tmp_im_2_ce0;
reg Tmp_im_2_we0;
reg Tmp_im_1_ce0;
reg Tmp_im_1_we0;
reg Tmp_im_ce0;
reg Tmp_im_we0;
reg Tmp_re_3_ce0;
reg Tmp_re_3_we0;
reg Tmp_re_2_ce0;
reg Tmp_re_2_we0;
reg Tmp_re_1_ce0;
reg Tmp_re_1_we0;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
wire    ap_block_state2_pp0_stage0_iter1;
wire    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln89_fu_632_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
wire   [63:0] zext_ln89_fu_678_p1;
reg   [63:0] zext_ln89_reg_907;
wire    ap_block_pp0_stage0_11001;
wire   [2:0] trunc_ln6_fu_738_p1;
reg   [2:0] trunc_ln6_reg_1079;
wire    ap_block_pp0_stage0;
wire   [63:0] zext_ln89_1_fu_718_p1;
reg   [3:0] j_fu_98;
wire   [3:0] add_ln90_fu_742_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_j_load;
reg   [2:0] i_fu_102;
wire   [2:0] select_ln89_1_fu_670_p3;
reg   [2:0] ap_sig_allocacmp_i_load;
reg   [5:0] indvar_flatten97_fu_106;
wire   [5:0] add_ln89_fu_638_p2;
reg   [5:0] ap_sig_allocacmp_indvar_flatten97_load;
wire   [63:0] add_ln9_fu_873_p2;
wire   [63:0] sub_ln8_fu_863_p2;
wire   [0:0] icmp_ln90_fu_650_p2;
wire   [2:0] add_ln89_1_fu_664_p2;
wire   [2:0] p_mid195_fu_698_p2;
wire   [2:0] empty_18_fu_704_p2;
wire   [2:0] select_ln89_2_fu_710_p3;
wire   [3:0] select_ln89_fu_656_p3;
wire   [62:0] a_re_fu_763_p10;
wire   [62:0] a_im_fu_788_p10;
wire   [62:0] in_re_fu_813_p10;
wire   [62:0] in_im_fu_838_p10;
wire  signed [63:0] sext_ln6_fu_784_p1;
wire  signed [63:0] sext_ln18_2_fu_859_p1;
wire  signed [63:0] sext_ln18_fu_834_p1;
wire  signed [63:0] sext_ln6_1_fu_809_p1;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

real_converter_mux_83_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 63 ),
    .din1_WIDTH( 63 ),
    .din2_WIDTH( 63 ),
    .din3_WIDTH( 63 ),
    .din4_WIDTH( 63 ),
    .din5_WIDTH( 63 ),
    .din6_WIDTH( 63 ),
    .din7_WIDTH( 63 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 63 ))
mux_83_63_1_1_U55(
    .din0(R_fb_re_q1),
    .din1(R_fb_re_1_q1),
    .din2(R_fb_re_2_q1),
    .din3(R_fb_re_3_q1),
    .din4(R_fb_re_4_q1),
    .din5(R_fb_re_5_q1),
    .din6(R_fb_re_6_q1),
    .din7(R_fb_re_7_q1),
    .din8(trunc_ln6_reg_1079),
    .dout(a_re_fu_763_p10)
);

real_converter_mux_83_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 63 ),
    .din1_WIDTH( 63 ),
    .din2_WIDTH( 63 ),
    .din3_WIDTH( 63 ),
    .din4_WIDTH( 63 ),
    .din5_WIDTH( 63 ),
    .din6_WIDTH( 63 ),
    .din7_WIDTH( 63 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 63 ))
mux_83_63_1_1_U56(
    .din0(R_fb_im_q1),
    .din1(R_fb_im_1_q1),
    .din2(R_fb_im_2_q1),
    .din3(R_fb_im_3_q1),
    .din4(R_fb_im_4_q1),
    .din5(R_fb_im_5_q1),
    .din6(R_fb_im_6_q1),
    .din7(R_fb_im_7_q1),
    .din8(trunc_ln6_reg_1079),
    .dout(a_im_fu_788_p10)
);

real_converter_mux_83_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 63 ),
    .din1_WIDTH( 63 ),
    .din2_WIDTH( 63 ),
    .din3_WIDTH( 63 ),
    .din4_WIDTH( 63 ),
    .din5_WIDTH( 63 ),
    .din6_WIDTH( 63 ),
    .din7_WIDTH( 63 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 63 ))
mux_83_63_1_1_U57(
    .din0(R_fb_re_q0),
    .din1(R_fb_re_1_q0),
    .din2(R_fb_re_2_q0),
    .din3(R_fb_re_3_q0),
    .din4(R_fb_re_4_q0),
    .din5(R_fb_re_5_q0),
    .din6(R_fb_re_6_q0),
    .din7(R_fb_re_7_q0),
    .din8(trunc_ln6_reg_1079),
    .dout(in_re_fu_813_p10)
);

real_converter_mux_83_63_1_1 #(
    .ID( 1 ),
    .NUM_STAGE( 1 ),
    .din0_WIDTH( 63 ),
    .din1_WIDTH( 63 ),
    .din2_WIDTH( 63 ),
    .din3_WIDTH( 63 ),
    .din4_WIDTH( 63 ),
    .din5_WIDTH( 63 ),
    .din6_WIDTH( 63 ),
    .din7_WIDTH( 63 ),
    .din8_WIDTH( 3 ),
    .dout_WIDTH( 63 ))
mux_83_63_1_1_U58(
    .din0(R_fb_im_q0),
    .din1(R_fb_im_1_q0),
    .din2(R_fb_im_2_q0),
    .din3(R_fb_im_3_q0),
    .din4(R_fb_im_4_q0),
    .din5(R_fb_im_5_q0),
    .din6(R_fb_im_6_q0),
    .din7(R_fb_im_7_q0),
    .din8(trunc_ln6_reg_1079),
    .dout(in_im_fu_838_p10)
);

real_converter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln89_fu_632_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_102 <= select_ln89_1_fu_670_p3;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_102 <= 3'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln89_fu_632_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            indvar_flatten97_fu_106 <= add_ln89_fu_638_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            indvar_flatten97_fu_106 <= 6'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln89_fu_632_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            j_fu_98 <= add_ln90_fu_742_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            j_fu_98 <= 4'd0;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((icmp_ln89_fu_632_p2 == 1'd0) & (1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        trunc_ln6_reg_1079 <= trunc_ln6_fu_738_p1;
        zext_ln89_reg_907[2 : 0] <= zext_ln89_fu_678_p1[2 : 0];
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_1_ce0 = 1'b1;
    end else begin
        R_fb_im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_1_ce1 = 1'b1;
    end else begin
        R_fb_im_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_2_ce0 = 1'b1;
    end else begin
        R_fb_im_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_2_ce1 = 1'b1;
    end else begin
        R_fb_im_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_3_ce0 = 1'b1;
    end else begin
        R_fb_im_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_3_ce1 = 1'b1;
    end else begin
        R_fb_im_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_4_ce0 = 1'b1;
    end else begin
        R_fb_im_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_4_ce1 = 1'b1;
    end else begin
        R_fb_im_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_5_ce0 = 1'b1;
    end else begin
        R_fb_im_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_5_ce1 = 1'b1;
    end else begin
        R_fb_im_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_6_ce0 = 1'b1;
    end else begin
        R_fb_im_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_6_ce1 = 1'b1;
    end else begin
        R_fb_im_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_7_ce0 = 1'b1;
    end else begin
        R_fb_im_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_7_ce1 = 1'b1;
    end else begin
        R_fb_im_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_ce0 = 1'b1;
    end else begin
        R_fb_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_im_ce1 = 1'b1;
    end else begin
        R_fb_im_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_1_ce0 = 1'b1;
    end else begin
        R_fb_re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_1_ce1 = 1'b1;
    end else begin
        R_fb_re_1_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_2_ce0 = 1'b1;
    end else begin
        R_fb_re_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_2_ce1 = 1'b1;
    end else begin
        R_fb_re_2_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_3_ce0 = 1'b1;
    end else begin
        R_fb_re_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_3_ce1 = 1'b1;
    end else begin
        R_fb_re_3_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_4_ce0 = 1'b1;
    end else begin
        R_fb_re_4_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_4_ce1 = 1'b1;
    end else begin
        R_fb_re_4_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_5_ce0 = 1'b1;
    end else begin
        R_fb_re_5_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_5_ce1 = 1'b1;
    end else begin
        R_fb_re_5_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_6_ce0 = 1'b1;
    end else begin
        R_fb_re_6_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_6_ce1 = 1'b1;
    end else begin
        R_fb_re_6_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_7_ce0 = 1'b1;
    end else begin
        R_fb_re_7_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_7_ce1 = 1'b1;
    end else begin
        R_fb_re_7_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_ce0 = 1'b1;
    end else begin
        R_fb_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_fb_re_ce1 = 1'b1;
    end else begin
        R_fb_re_ce1 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_1_ce0 = 1'b1;
    end else begin
        Tmp_im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd5) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_1_we0 = 1'b1;
    end else begin
        Tmp_im_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_2_ce0 = 1'b1;
    end else begin
        Tmp_im_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd6) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_2_we0 = 1'b1;
    end else begin
        Tmp_im_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_3_ce0 = 1'b1;
    end else begin
        Tmp_im_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd7) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_3_we0 = 1'b1;
    end else begin
        Tmp_im_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_ce0 = 1'b1;
    end else begin
        Tmp_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd4) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_we0 = 1'b1;
    end else begin
        Tmp_im_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_1_ce0 = 1'b1;
    end else begin
        Tmp_re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd1) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_1_we0 = 1'b1;
    end else begin
        Tmp_re_1_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_2_ce0 = 1'b1;
    end else begin
        Tmp_re_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd2) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_2_we0 = 1'b1;
    end else begin
        Tmp_re_2_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_3_ce0 = 1'b1;
    end else begin
        Tmp_re_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd3) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_3_we0 = 1'b1;
    end else begin
        Tmp_re_3_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_ce0 = 1'b1;
    end else begin
        Tmp_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (trunc_ln6_reg_1079 == 3'd0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_we0 = 1'b1;
    end else begin
        Tmp_re_we0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln89_fu_632_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_i_load = 3'd0;
    end else begin
        ap_sig_allocacmp_i_load = i_fu_102;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_indvar_flatten97_load = 6'd0;
    end else begin
        ap_sig_allocacmp_indvar_flatten97_load = indvar_flatten97_fu_106;
    end
end

always @ (*) begin
    if (((ap_loop_init == 1'b1) & (1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_sig_allocacmp_j_load = 4'd0;
    end else begin
        ap_sig_allocacmp_j_load = j_fu_98;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_fb_im_1_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_1_address1 = zext_ln89_fu_678_p1;

assign R_fb_im_2_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_2_address1 = zext_ln89_fu_678_p1;

assign R_fb_im_3_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_3_address1 = zext_ln89_fu_678_p1;

assign R_fb_im_4_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_4_address1 = zext_ln89_fu_678_p1;

assign R_fb_im_5_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_5_address1 = zext_ln89_fu_678_p1;

assign R_fb_im_6_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_6_address1 = zext_ln89_fu_678_p1;

assign R_fb_im_7_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_7_address1 = zext_ln89_fu_678_p1;

assign R_fb_im_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_im_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_1_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_1_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_2_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_2_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_3_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_3_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_4_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_4_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_5_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_5_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_6_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_6_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_7_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_7_address1 = zext_ln89_fu_678_p1;

assign R_fb_re_address0 = zext_ln89_1_fu_718_p1;

assign R_fb_re_address1 = zext_ln89_fu_678_p1;

assign Tmp_im_1_address0 = zext_ln89_reg_907;

assign Tmp_im_1_d0 = add_ln9_fu_873_p2;

assign Tmp_im_2_address0 = zext_ln89_reg_907;

assign Tmp_im_2_d0 = add_ln9_fu_873_p2;

assign Tmp_im_3_address0 = zext_ln89_reg_907;

assign Tmp_im_3_d0 = add_ln9_fu_873_p2;

assign Tmp_im_address0 = zext_ln89_reg_907;

assign Tmp_im_d0 = add_ln9_fu_873_p2;

assign Tmp_re_1_address0 = zext_ln89_reg_907;

assign Tmp_re_1_d0 = sub_ln8_fu_863_p2;

assign Tmp_re_2_address0 = zext_ln89_reg_907;

assign Tmp_re_2_d0 = sub_ln8_fu_863_p2;

assign Tmp_re_3_address0 = zext_ln89_reg_907;

assign Tmp_re_3_d0 = sub_ln8_fu_863_p2;

assign Tmp_re_address0 = zext_ln89_reg_907;

assign Tmp_re_d0 = sub_ln8_fu_863_p2;

assign add_ln89_1_fu_664_p2 = (ap_sig_allocacmp_i_load + 3'd1);

assign add_ln89_fu_638_p2 = (ap_sig_allocacmp_indvar_flatten97_load + 6'd1);

assign add_ln90_fu_742_p2 = (select_ln89_fu_656_p3 + 4'd1);

assign add_ln9_fu_873_p2 = ($signed(sext_ln18_fu_834_p1) + $signed(sext_ln6_1_fu_809_p1));

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_11001 = ~(1'b1 == 1'b1);

assign ap_block_pp0_stage0_subdone = ~(1'b1 == 1'b1);

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

assign ap_block_state2_pp0_stage0_iter1 = ~(1'b1 == 1'b1);

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign empty_18_fu_704_p2 = (ap_sig_allocacmp_i_load ^ 3'd4);

assign icmp_ln89_fu_632_p2 = ((ap_sig_allocacmp_indvar_flatten97_load == 6'd32) ? 1'b1 : 1'b0);

assign icmp_ln90_fu_650_p2 = ((ap_sig_allocacmp_j_load == 4'd8) ? 1'b1 : 1'b0);

assign p_mid195_fu_698_p2 = (ap_sig_allocacmp_i_load + 3'd5);

assign select_ln89_1_fu_670_p3 = ((icmp_ln90_fu_650_p2[0:0] == 1'b1) ? add_ln89_1_fu_664_p2 : ap_sig_allocacmp_i_load);

assign select_ln89_2_fu_710_p3 = ((icmp_ln90_fu_650_p2[0:0] == 1'b1) ? p_mid195_fu_698_p2 : empty_18_fu_704_p2);

assign select_ln89_fu_656_p3 = ((icmp_ln90_fu_650_p2[0:0] == 1'b1) ? 4'd0 : ap_sig_allocacmp_j_load);

assign sext_ln18_2_fu_859_p1 = $signed(in_im_fu_838_p10);

assign sext_ln18_fu_834_p1 = $signed(in_re_fu_813_p10);

assign sext_ln6_1_fu_809_p1 = $signed(a_im_fu_788_p10);

assign sext_ln6_fu_784_p1 = $signed(a_re_fu_763_p10);

assign sub_ln8_fu_863_p2 = ($signed(sext_ln6_fu_784_p1) - $signed(sext_ln18_2_fu_859_p1));

assign trunc_ln6_fu_738_p1 = select_ln89_fu_656_p3[2:0];

assign zext_ln89_1_fu_718_p1 = select_ln89_2_fu_710_p3;

assign zext_ln89_fu_678_p1 = select_ln89_1_fu_670_p3;

always @ (posedge ap_clk) begin
    zext_ln89_reg_907[63:3] <= 61'b0000000000000000000000000000000000000000000000000000000000000;
end

endmodule //real_converter_real_converter_Pipeline_Q1_ROW_Q1_COL
