// ==============================================================
// RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
// Version: 2022.2
// Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
// 
// ===========================================================

`timescale 1 ns / 1 ps 

module real_converter_real_converter_Pipeline_OUT_ROW (
        ap_clk,
        ap_rst,
        ap_start,
        ap_done,
        ap_idle,
        ap_ready,
        R_out_TREADY,
        Tmp_re_address0,
        Tmp_re_ce0,
        Tmp_re_q0,
        Tmp_im_address0,
        Tmp_im_ce0,
        Tmp_im_q0,
        Tmp_re_1_address0,
        Tmp_re_1_ce0,
        Tmp_re_1_q0,
        Tmp_im_1_address0,
        Tmp_im_1_ce0,
        Tmp_im_1_q0,
        Tmp_re_2_address0,
        Tmp_re_2_ce0,
        Tmp_re_2_q0,
        Tmp_im_2_address0,
        Tmp_im_2_ce0,
        Tmp_im_2_q0,
        Tmp_re_3_address0,
        Tmp_re_3_ce0,
        Tmp_re_3_q0,
        Tmp_im_3_address0,
        Tmp_im_3_ce0,
        Tmp_im_3_q0,
        R_out_TDATA,
        R_out_TVALID
);

parameter    ap_ST_fsm_pp0_stage0 = 1'd1;

input   ap_clk;
input   ap_rst;
input   ap_start;
output   ap_done;
output   ap_idle;
output   ap_ready;
input   R_out_TREADY;
output  [2:0] Tmp_re_address0;
output   Tmp_re_ce0;
input  [63:0] Tmp_re_q0;
output  [2:0] Tmp_im_address0;
output   Tmp_im_ce0;
input  [63:0] Tmp_im_q0;
output  [2:0] Tmp_re_1_address0;
output   Tmp_re_1_ce0;
input  [63:0] Tmp_re_1_q0;
output  [2:0] Tmp_im_1_address0;
output   Tmp_im_1_ce0;
input  [63:0] Tmp_im_1_q0;
output  [2:0] Tmp_re_2_address0;
output   Tmp_re_2_ce0;
input  [63:0] Tmp_re_2_q0;
output  [2:0] Tmp_im_2_address0;
output   Tmp_im_2_ce0;
input  [63:0] Tmp_im_2_q0;
output  [2:0] Tmp_re_3_address0;
output   Tmp_re_3_ce0;
input  [63:0] Tmp_re_3_q0;
output  [2:0] Tmp_im_3_address0;
output   Tmp_im_3_ce0;
input  [63:0] Tmp_im_3_q0;
output  [511:0] R_out_TDATA;
output   R_out_TVALID;

reg ap_idle;
reg Tmp_re_ce0;
reg Tmp_im_ce0;
reg Tmp_re_1_ce0;
reg Tmp_im_1_ce0;
reg Tmp_re_2_ce0;
reg Tmp_im_2_ce0;
reg Tmp_re_3_ce0;
reg Tmp_im_3_ce0;
reg R_out_TVALID;

(* fsm_encoding = "none" *) reg   [0:0] ap_CS_fsm;
wire    ap_CS_fsm_pp0_stage0;
wire    ap_enable_reg_pp0_iter0;
reg    ap_enable_reg_pp0_iter1;
reg    ap_idle_pp0;
wire    ap_block_state1_pp0_stage0_iter0;
reg    ap_block_state2_pp0_stage0_iter1;
reg    ap_block_pp0_stage0_subdone;
wire   [0:0] icmp_ln117_fu_199_p2;
reg    ap_condition_exit_pp0_iter0_stage0;
wire    ap_loop_exit_ready;
reg    ap_ready_int;
reg    R_out_TDATA_blk_n;
wire    ap_block_pp0_stage0;
reg    ap_block_pp0_stage0_11001;
wire   [63:0] zext_ln117_fu_211_p1;
reg   [3:0] i_fu_76;
wire   [3:0] add_ln117_fu_205_p2;
wire    ap_loop_init;
reg   [3:0] ap_sig_allocacmp_i_1;
reg    ap_block_pp0_stage0_01001;
wire   [63:0] res_real_fu_228_p2;
wire   [62:0] out_row_packed_cols_fu_234_p4;
wire   [63:0] res_real_1_fu_248_p2;
wire   [63:0] res_real_2_fu_264_p2;
wire   [63:0] res_real_3_fu_280_p2;
wire   [63:0] res_real_4_fu_296_p2;
wire   [63:0] res_real_6_fu_318_p2;
wire   [63:0] res_real_7_fu_334_p2;
wire   [62:0] trunc_ln7_fu_254_p4;
wire   [62:0] trunc_ln135_1_fu_270_p4;
wire   [62:0] trunc_ln135_2_fu_286_p4;
wire   [63:0] res_real_5_fu_312_p2;
wire   [0:0] tmp_fu_362_p3;
wire  signed [63:0] sext_ln138_1_fu_354_p1;
wire   [62:0] trunc_ln135_3_fu_302_p4;
wire  signed [63:0] sext_ln138_2_fu_358_p1;
wire  signed [63:0] sext_ln138_fu_350_p1;
wire  signed [63:0] sext_ln135_fu_244_p1;
wire   [318:0] or_ln_fu_382_p6;
wire  signed [319:0] sext_ln138_3_fu_396_p1;
wire   [320:0] tmp_1_fu_370_p5;
wire   [320:0] tmp_s_fu_400_p3;
wire   [61:0] tmp_2_fu_414_p4;
wire   [62:0] trunc_ln135_5_fu_324_p4;
wire  signed [62:0] sext_ln138_4_fu_424_p1;
wire   [320:0] or_ln138_fu_408_p2;
wire   [446:0] or_ln138_1_fu_428_p4;
wire   [62:0] trunc_ln135_6_fu_340_p4;
wire  signed [447:0] sext_ln138_5_fu_438_p1;
wire   [510:0] or_ln138_5_fu_442_p3;
reg    ap_done_reg;
wire    ap_continue_int;
reg    ap_done_int;
reg   [0:0] ap_NS_fsm;
wire    ap_enable_pp0;
wire    ap_start_int;
wire    ap_ce_reg;

// power-on initialization
initial begin
#0 ap_CS_fsm = 1'd1;
#0 ap_enable_reg_pp0_iter1 = 1'b0;
#0 ap_done_reg = 1'b0;
end

real_converter_flow_control_loop_pipe_sequential_init flow_control_loop_pipe_sequential_init_U(
    .ap_clk(ap_clk),
    .ap_rst(ap_rst),
    .ap_start(ap_start),
    .ap_ready(ap_ready),
    .ap_done(ap_done),
    .ap_start_int(ap_start_int),
    .ap_loop_init(ap_loop_init),
    .ap_ready_int(ap_ready_int),
    .ap_loop_exit_ready(ap_condition_exit_pp0_iter0_stage0),
    .ap_loop_exit_done(ap_done_int),
    .ap_continue_int(ap_continue_int),
    .ap_done_int(ap_done_int)
);

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
    end else begin
        ap_CS_fsm <= ap_NS_fsm;
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_done_reg <= 1'b0;
    end else begin
        if ((ap_continue_int == 1'b1)) begin
            ap_done_reg <= 1'b0;
        end else if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_done_reg <= 1'b1;
        end
    end
end

always @ (posedge ap_clk) begin
    if (ap_rst == 1'b1) begin
        ap_enable_reg_pp0_iter1 <= 1'b0;
    end else begin
        if ((1'b1 == ap_condition_exit_pp0_iter0_stage0)) begin
            ap_enable_reg_pp0_iter1 <= 1'b0;
        end else if (((1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
            ap_enable_reg_pp0_iter1 <= ap_start_int;
        end
    end
end

always @ (posedge ap_clk) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        if (((icmp_ln117_fu_199_p2 == 1'd0) & (ap_enable_reg_pp0_iter0 == 1'b1))) begin
            i_fu_76 <= add_ln117_fu_205_p2;
        end else if ((ap_loop_init == 1'b1)) begin
            i_fu_76 <= 4'd0;
        end
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_out_TDATA_blk_n = R_out_TREADY;
    end else begin
        R_out_TDATA_blk_n = 1'b1;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter1 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        R_out_TVALID = 1'b1;
    end else begin
        R_out_TVALID = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_1_ce0 = 1'b1;
    end else begin
        Tmp_im_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_2_ce0 = 1'b1;
    end else begin
        Tmp_im_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_3_ce0 = 1'b1;
    end else begin
        Tmp_im_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_im_ce0 = 1'b1;
    end else begin
        Tmp_im_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_1_ce0 = 1'b1;
    end else begin
        Tmp_re_1_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_2_ce0 = 1'b1;
    end else begin
        Tmp_re_2_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_3_ce0 = 1'b1;
    end else begin
        Tmp_re_3_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_11001) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        Tmp_re_ce0 = 1'b1;
    end else begin
        Tmp_re_ce0 = 1'b0;
    end
end

always @ (*) begin
    if (((icmp_ln117_fu_199_p2 == 1'd1) & (1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b1;
    end else begin
        ap_condition_exit_pp0_iter0_stage0 = 1'b0;
    end
end

always @ (*) begin
    if (((ap_loop_exit_ready == 1'b1) & (1'b0 == ap_block_pp0_stage0_subdone) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_done_int = 1'b1;
    end else begin
        ap_done_int = ap_done_reg;
    end
end

always @ (*) begin
    if (((ap_start_int == 1'b0) & (ap_idle_pp0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_idle = 1'b1;
    end else begin
        ap_idle = 1'b0;
    end
end

always @ (*) begin
    if (((ap_enable_reg_pp0_iter1 == 1'b0) & (ap_enable_reg_pp0_iter0 == 1'b0))) begin
        ap_idle_pp0 = 1'b1;
    end else begin
        ap_idle_pp0 = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0_subdone) & (ap_enable_reg_pp0_iter0 == 1'b1) & (1'b1 == ap_CS_fsm_pp0_stage0))) begin
        ap_ready_int = 1'b1;
    end else begin
        ap_ready_int = 1'b0;
    end
end

always @ (*) begin
    if (((1'b0 == ap_block_pp0_stage0) & (1'b1 == ap_CS_fsm_pp0_stage0) & (ap_loop_init == 1'b1))) begin
        ap_sig_allocacmp_i_1 = 4'd0;
    end else begin
        ap_sig_allocacmp_i_1 = i_fu_76;
    end
end

always @ (*) begin
    case (ap_CS_fsm)
        ap_ST_fsm_pp0_stage0 : begin
            ap_NS_fsm = ap_ST_fsm_pp0_stage0;
        end
        default : begin
            ap_NS_fsm = 'bx;
        end
    endcase
end

assign R_out_TDATA = $signed(or_ln138_5_fu_442_p3);

assign Tmp_im_1_address0 = zext_ln117_fu_211_p1;

assign Tmp_im_2_address0 = zext_ln117_fu_211_p1;

assign Tmp_im_3_address0 = zext_ln117_fu_211_p1;

assign Tmp_im_address0 = zext_ln117_fu_211_p1;

assign Tmp_re_1_address0 = zext_ln117_fu_211_p1;

assign Tmp_re_2_address0 = zext_ln117_fu_211_p1;

assign Tmp_re_3_address0 = zext_ln117_fu_211_p1;

assign Tmp_re_address0 = zext_ln117_fu_211_p1;

assign add_ln117_fu_205_p2 = (ap_sig_allocacmp_i_1 + 4'd1);

assign ap_CS_fsm_pp0_stage0 = ap_CS_fsm[32'd0];

assign ap_block_pp0_stage0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_pp0_stage0_01001 = ((1'b0 == R_out_TREADY) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_11001 = ((1'b0 == R_out_TREADY) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

always @ (*) begin
    ap_block_pp0_stage0_subdone = ((1'b0 == R_out_TREADY) & (ap_enable_reg_pp0_iter1 == 1'b1));
end

assign ap_block_state1_pp0_stage0_iter0 = ~(1'b1 == 1'b1);

always @ (*) begin
    ap_block_state2_pp0_stage0_iter1 = (1'b0 == R_out_TREADY);
end

assign ap_enable_pp0 = (ap_idle_pp0 ^ 1'b1);

assign ap_enable_reg_pp0_iter0 = ap_start_int;

assign ap_loop_exit_ready = ap_condition_exit_pp0_iter0_stage0;

assign icmp_ln117_fu_199_p2 = ((ap_sig_allocacmp_i_1 == 4'd8) ? 1'b1 : 1'b0);

assign or_ln138_1_fu_428_p4 = {{{trunc_ln135_5_fu_324_p4}, {sext_ln138_4_fu_424_p1}}, {or_ln138_fu_408_p2}};

assign or_ln138_5_fu_442_p3 = {{trunc_ln135_6_fu_340_p4}, {sext_ln138_5_fu_438_p1}};

assign or_ln138_fu_408_p2 = (tmp_s_fu_400_p3 | tmp_1_fu_370_p5);

assign or_ln_fu_382_p6 = {{{{{trunc_ln135_3_fu_302_p4}, {sext_ln138_2_fu_358_p1}}, {64'd0}}, {sext_ln138_fu_350_p1}}, {sext_ln135_fu_244_p1}};

assign out_row_packed_cols_fu_234_p4 = {{res_real_fu_228_p2[63:1]}};

assign res_real_1_fu_248_p2 = (Tmp_im_1_q0 + Tmp_re_1_q0);

assign res_real_2_fu_264_p2 = (Tmp_im_2_q0 + Tmp_re_2_q0);

assign res_real_3_fu_280_p2 = (Tmp_im_3_q0 + Tmp_re_3_q0);

assign res_real_4_fu_296_p2 = (Tmp_re_3_q0 - Tmp_im_3_q0);

assign res_real_5_fu_312_p2 = (Tmp_re_2_q0 - Tmp_im_2_q0);

assign res_real_6_fu_318_p2 = (Tmp_re_1_q0 - Tmp_im_1_q0);

assign res_real_7_fu_334_p2 = (Tmp_re_q0 - Tmp_im_q0);

assign res_real_fu_228_p2 = (Tmp_im_q0 + Tmp_re_q0);

assign sext_ln135_fu_244_p1 = $signed(out_row_packed_cols_fu_234_p4);

assign sext_ln138_1_fu_354_p1 = $signed(trunc_ln135_1_fu_270_p4);

assign sext_ln138_2_fu_358_p1 = $signed(trunc_ln135_2_fu_286_p4);

assign sext_ln138_3_fu_396_p1 = $signed(or_ln_fu_382_p6);

assign sext_ln138_4_fu_424_p1 = $signed(tmp_2_fu_414_p4);

assign sext_ln138_5_fu_438_p1 = $signed(or_ln138_1_fu_428_p4);

assign sext_ln138_fu_350_p1 = $signed(trunc_ln7_fu_254_p4);

assign tmp_1_fu_370_p5 = {{{{tmp_fu_362_p3}, {128'd0}}, {sext_ln138_1_fu_354_p1}}, {128'd0}};

assign tmp_2_fu_414_p4 = {{res_real_5_fu_312_p2[63:2]}};

assign tmp_fu_362_p3 = res_real_5_fu_312_p2[32'd1];

assign tmp_s_fu_400_p3 = {{1'd0}, {sext_ln138_3_fu_396_p1}};

assign trunc_ln135_1_fu_270_p4 = {{res_real_2_fu_264_p2[63:1]}};

assign trunc_ln135_2_fu_286_p4 = {{res_real_3_fu_280_p2[63:1]}};

assign trunc_ln135_3_fu_302_p4 = {{res_real_4_fu_296_p2[63:1]}};

assign trunc_ln135_5_fu_324_p4 = {{res_real_6_fu_318_p2[63:1]}};

assign trunc_ln135_6_fu_340_p4 = {{res_real_7_fu_334_p2[63:1]}};

assign trunc_ln7_fu_254_p4 = {{res_real_1_fu_248_p2[63:1]}};

assign zext_ln117_fu_211_p1 = ap_sig_allocacmp_i_1;

endmodule //real_converter_real_converter_Pipeline_OUT_ROW
