COMPILER=
ARCHIVER=
CP=cp
COMPILER_FLAGS=
EXTRA_COMPILER_FLAGS=
LIB=libxil.a

RELEASEDIR=../../../lib
INCLUDEDIR=../../../include
INCLUDES=-I./. -I${INCLUDEDIR}

INCLUDEFILES=adau1979_capture.h

libs:
	echo "Compiling adau1979_capture..."
	$(CP) $(INCLUDEFILES) $(INCLUDEDIR)

clean:
	echo "Nothing to clean."
