# ADAU1979 capture IP pin constraints template.
#
# Important:
# 1. Replace every <PIN_...> with the real Zynq-7020 package pin connected to
#    the ADAU1979 board H4 connector.
# 2. If Vivado Block Design auto-renames external ports, first run:
#       get_ports *adau*
#    Then replace adau_scl/adau_sda/... below with the actual top-level names,
#    for example adau_scl_0 or adau1979_capture_0_adau_scl.
#
# ADAU1979 board H4 order:
#   H4-1  SCL
#   H4-2  SDA
#   H4-3  BCLK
#   H4-4  LCLK / LRCLK
#   H4-5  SDATAOUT02 = U1 channel 3/4
#   H4-6  SDATAOUT01 = U1 channel 1/2
#   H4-7  SDATAOUT12 = U2 channel 3/4
#   H4-8  SDATAOUT11 = U2 channel 1/2
#   H4-9  PD/RST
#   H4-10 GND
#
# IP channel mapping:
#   adau_sdata[0] = U1 SDATAOUT01 = U1C1/U1C2
#   adau_sdata[1] = U1 SDATAOUT02 = U1C3/U1C4
#   adau_sdata[2] = U2 SDATAOUT11 = U2C1/U2C2
#   adau_sdata[3] = U2 SDATAOUT12 = U2C3/U2C4

set_property PACKAGE_PIN <PIN_H4_1_SCL>        [get_ports adau_scl]
set_property PACKAGE_PIN <PIN_H4_2_SDA>        [get_ports adau_sda]
set_property PACKAGE_PIN <PIN_H4_3_BCLK>       [get_ports adau_bclk]
set_property PACKAGE_PIN <PIN_H4_4_LRCLK>      [get_ports adau_lrclk]
set_property PACKAGE_PIN <PIN_H4_5_SDATAOUT02> [get_ports {adau_sdata[1]}]
set_property PACKAGE_PIN <PIN_H4_6_SDATAOUT01> [get_ports {adau_sdata[0]}]
set_property PACKAGE_PIN <PIN_H4_7_SDATAOUT12> [get_ports {adau_sdata[3]}]
set_property PACKAGE_PIN <PIN_H4_8_SDATAOUT11> [get_ports {adau_sdata[2]}]
set_property PACKAGE_PIN <PIN_H4_9_PD_RST>     [get_ports adau_pd_rst]

set_property IOSTANDARD LVCMOS33 [get_ports adau_scl]
set_property IOSTANDARD LVCMOS33 [get_ports adau_sda]
set_property IOSTANDARD LVCMOS33 [get_ports adau_bclk]
set_property IOSTANDARD LVCMOS33 [get_ports adau_lrclk]
set_property IOSTANDARD LVCMOS33 [get_ports {adau_sdata[*]}]
set_property IOSTANDARD LVCMOS33 [get_ports adau_pd_rst]

# SCL/SDA are open-drain I2C lines. The ADAU1979 board schematic already has
# pull-up resistors. SCL is output-only because this IP does not support clock
# stretching; SDA remains an inout port for ACK and register reads.
#
# Enable weak FPGA pull-ups only for bring-up if the external pull-ups are not
# populated:
# set_property PULLUP true [get_ports adau_scl]
# set_property PULLUP true [get_ports adau_sda]

# BCLK/LRCLK/SDATA are generated by the ADAU1979 audio clock domain and sampled
# by the 100 MHz PL clock inside the IP with synchronizer registers. Mark the
# direct pad-to-register paths as asynchronous to avoid false timing failures.
set_false_path -from [get_ports adau_bclk]
set_false_path -from [get_ports adau_lrclk]
set_false_path -from [get_ports {adau_sdata[*]}]
