-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity real_converter_real_converter_Pipeline_Q1_ROW_Q1_COL is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    Tmp_re_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_ce0 : OUT STD_LOGIC;
    Tmp_re_we0 : OUT STD_LOGIC;
    Tmp_re_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_fb_re_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_ce0 : OUT STD_LOGIC;
    R_fb_re_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_ce1 : OUT STD_LOGIC;
    R_fb_re_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_1_ce0 : OUT STD_LOGIC;
    R_fb_re_1_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_1_ce1 : OUT STD_LOGIC;
    R_fb_re_1_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_2_ce0 : OUT STD_LOGIC;
    R_fb_re_2_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_2_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_2_ce1 : OUT STD_LOGIC;
    R_fb_re_2_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_3_ce0 : OUT STD_LOGIC;
    R_fb_re_3_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_3_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_3_ce1 : OUT STD_LOGIC;
    R_fb_re_3_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_4_ce0 : OUT STD_LOGIC;
    R_fb_re_4_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_4_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_4_ce1 : OUT STD_LOGIC;
    R_fb_re_4_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_5_ce0 : OUT STD_LOGIC;
    R_fb_re_5_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_5_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_5_ce1 : OUT STD_LOGIC;
    R_fb_re_5_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_6_ce0 : OUT STD_LOGIC;
    R_fb_re_6_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_6_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_6_ce1 : OUT STD_LOGIC;
    R_fb_re_6_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_7_ce0 : OUT STD_LOGIC;
    R_fb_re_7_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_re_7_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_re_7_ce1 : OUT STD_LOGIC;
    R_fb_re_7_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_ce0 : OUT STD_LOGIC;
    R_fb_im_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_ce1 : OUT STD_LOGIC;
    R_fb_im_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_1_ce0 : OUT STD_LOGIC;
    R_fb_im_1_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_1_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_1_ce1 : OUT STD_LOGIC;
    R_fb_im_1_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_2_ce0 : OUT STD_LOGIC;
    R_fb_im_2_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_2_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_2_ce1 : OUT STD_LOGIC;
    R_fb_im_2_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_3_ce0 : OUT STD_LOGIC;
    R_fb_im_3_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_3_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_3_ce1 : OUT STD_LOGIC;
    R_fb_im_3_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_4_ce0 : OUT STD_LOGIC;
    R_fb_im_4_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_4_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_4_ce1 : OUT STD_LOGIC;
    R_fb_im_4_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_5_ce0 : OUT STD_LOGIC;
    R_fb_im_5_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_5_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_5_ce1 : OUT STD_LOGIC;
    R_fb_im_5_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_6_ce0 : OUT STD_LOGIC;
    R_fb_im_6_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_6_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_6_ce1 : OUT STD_LOGIC;
    R_fb_im_6_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_7_ce0 : OUT STD_LOGIC;
    R_fb_im_7_q0 : IN STD_LOGIC_VECTOR (62 downto 0);
    R_fb_im_7_address1 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_fb_im_7_ce1 : OUT STD_LOGIC;
    R_fb_im_7_q1 : IN STD_LOGIC_VECTOR (62 downto 0);
    Tmp_im_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_3_ce0 : OUT STD_LOGIC;
    Tmp_im_3_we0 : OUT STD_LOGIC;
    Tmp_im_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    Tmp_im_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_2_ce0 : OUT STD_LOGIC;
    Tmp_im_2_we0 : OUT STD_LOGIC;
    Tmp_im_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    Tmp_im_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_1_ce0 : OUT STD_LOGIC;
    Tmp_im_1_we0 : OUT STD_LOGIC;
    Tmp_im_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    Tmp_im_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_ce0 : OUT STD_LOGIC;
    Tmp_im_we0 : OUT STD_LOGIC;
    Tmp_im_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    Tmp_re_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_3_ce0 : OUT STD_LOGIC;
    Tmp_re_3_we0 : OUT STD_LOGIC;
    Tmp_re_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    Tmp_re_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_2_ce0 : OUT STD_LOGIC;
    Tmp_re_2_we0 : OUT STD_LOGIC;
    Tmp_re_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    Tmp_re_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_1_ce0 : OUT STD_LOGIC;
    Tmp_re_1_we0 : OUT STD_LOGIC;
    Tmp_re_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0) );
end;


architecture behav of real_converter_real_converter_Pipeline_Q1_ROW_Q1_COL is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv3_6 : STD_LOGIC_VECTOR (2 downto 0) := "110";
    constant ap_const_lv3_5 : STD_LOGIC_VECTOR (2 downto 0) := "101";
    constant ap_const_lv3_4 : STD_LOGIC_VECTOR (2 downto 0) := "100";
    constant ap_const_lv3_3 : STD_LOGIC_VECTOR (2 downto 0) := "011";
    constant ap_const_lv3_2 : STD_LOGIC_VECTOR (2 downto 0) := "010";
    constant ap_const_lv3_1 : STD_LOGIC_VECTOR (2 downto 0) := "001";
    constant ap_const_lv3_0 : STD_LOGIC_VECTOR (2 downto 0) := "000";
    constant ap_const_lv3_7 : STD_LOGIC_VECTOR (2 downto 0) := "111";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv6_0 : STD_LOGIC_VECTOR (5 downto 0) := "000000";
    constant ap_const_lv6_20 : STD_LOGIC_VECTOR (5 downto 0) := "100000";
    constant ap_const_lv6_1 : STD_LOGIC_VECTOR (5 downto 0) := "000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln89_fu_632_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal zext_ln89_fu_678_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal zext_ln89_reg_907 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal trunc_ln6_fu_738_p1 : STD_LOGIC_VECTOR (2 downto 0);
    signal trunc_ln6_reg_1079 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal zext_ln89_1_fu_718_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal j_fu_98 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln90_fu_742_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_j_load : STD_LOGIC_VECTOR (3 downto 0);
    signal i_fu_102 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln89_1_fu_670_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal ap_sig_allocacmp_i_load : STD_LOGIC_VECTOR (2 downto 0);
    signal indvar_flatten97_fu_106 : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln89_fu_638_p2 : STD_LOGIC_VECTOR (5 downto 0);
    signal ap_sig_allocacmp_indvar_flatten97_load : STD_LOGIC_VECTOR (5 downto 0);
    signal add_ln9_fu_873_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal sub_ln8_fu_863_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal icmp_ln90_fu_650_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal add_ln89_1_fu_664_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal p_mid195_fu_698_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal empty_18_fu_704_p2 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln89_2_fu_710_p3 : STD_LOGIC_VECTOR (2 downto 0);
    signal select_ln89_fu_656_p3 : STD_LOGIC_VECTOR (3 downto 0);
    signal a_re_fu_763_p10 : STD_LOGIC_VECTOR (62 downto 0);
    signal a_im_fu_788_p10 : STD_LOGIC_VECTOR (62 downto 0);
    signal in_re_fu_813_p10 : STD_LOGIC_VECTOR (62 downto 0);
    signal in_im_fu_838_p10 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln6_fu_784_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln18_2_fu_859_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln18_fu_834_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln6_1_fu_809_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component real_converter_mux_83_63_1_1 IS
    generic (
        ID : INTEGER;
        NUM_STAGE : INTEGER;
        din0_WIDTH : INTEGER;
        din1_WIDTH : INTEGER;
        din2_WIDTH : INTEGER;
        din3_WIDTH : INTEGER;
        din4_WIDTH : INTEGER;
        din5_WIDTH : INTEGER;
        din6_WIDTH : INTEGER;
        din7_WIDTH : INTEGER;
        din8_WIDTH : INTEGER;
        dout_WIDTH : INTEGER );
    port (
        din0 : IN STD_LOGIC_VECTOR (62 downto 0);
        din1 : IN STD_LOGIC_VECTOR (62 downto 0);
        din2 : IN STD_LOGIC_VECTOR (62 downto 0);
        din3 : IN STD_LOGIC_VECTOR (62 downto 0);
        din4 : IN STD_LOGIC_VECTOR (62 downto 0);
        din5 : IN STD_LOGIC_VECTOR (62 downto 0);
        din6 : IN STD_LOGIC_VECTOR (62 downto 0);
        din7 : IN STD_LOGIC_VECTOR (62 downto 0);
        din8 : IN STD_LOGIC_VECTOR (2 downto 0);
        dout : OUT STD_LOGIC_VECTOR (62 downto 0) );
    end component;


    component real_converter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    mux_83_63_1_1_U55 : component real_converter_mux_83_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 63,
        din1_WIDTH => 63,
        din2_WIDTH => 63,
        din3_WIDTH => 63,
        din4_WIDTH => 63,
        din5_WIDTH => 63,
        din6_WIDTH => 63,
        din7_WIDTH => 63,
        din8_WIDTH => 3,
        dout_WIDTH => 63)
    port map (
        din0 => R_fb_re_q1,
        din1 => R_fb_re_1_q1,
        din2 => R_fb_re_2_q1,
        din3 => R_fb_re_3_q1,
        din4 => R_fb_re_4_q1,
        din5 => R_fb_re_5_q1,
        din6 => R_fb_re_6_q1,
        din7 => R_fb_re_7_q1,
        din8 => trunc_ln6_reg_1079,
        dout => a_re_fu_763_p10);

    mux_83_63_1_1_U56 : component real_converter_mux_83_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 63,
        din1_WIDTH => 63,
        din2_WIDTH => 63,
        din3_WIDTH => 63,
        din4_WIDTH => 63,
        din5_WIDTH => 63,
        din6_WIDTH => 63,
        din7_WIDTH => 63,
        din8_WIDTH => 3,
        dout_WIDTH => 63)
    port map (
        din0 => R_fb_im_q1,
        din1 => R_fb_im_1_q1,
        din2 => R_fb_im_2_q1,
        din3 => R_fb_im_3_q1,
        din4 => R_fb_im_4_q1,
        din5 => R_fb_im_5_q1,
        din6 => R_fb_im_6_q1,
        din7 => R_fb_im_7_q1,
        din8 => trunc_ln6_reg_1079,
        dout => a_im_fu_788_p10);

    mux_83_63_1_1_U57 : component real_converter_mux_83_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 63,
        din1_WIDTH => 63,
        din2_WIDTH => 63,
        din3_WIDTH => 63,
        din4_WIDTH => 63,
        din5_WIDTH => 63,
        din6_WIDTH => 63,
        din7_WIDTH => 63,
        din8_WIDTH => 3,
        dout_WIDTH => 63)
    port map (
        din0 => R_fb_re_q0,
        din1 => R_fb_re_1_q0,
        din2 => R_fb_re_2_q0,
        din3 => R_fb_re_3_q0,
        din4 => R_fb_re_4_q0,
        din5 => R_fb_re_5_q0,
        din6 => R_fb_re_6_q0,
        din7 => R_fb_re_7_q0,
        din8 => trunc_ln6_reg_1079,
        dout => in_re_fu_813_p10);

    mux_83_63_1_1_U58 : component real_converter_mux_83_63_1_1
    generic map (
        ID => 1,
        NUM_STAGE => 1,
        din0_WIDTH => 63,
        din1_WIDTH => 63,
        din2_WIDTH => 63,
        din3_WIDTH => 63,
        din4_WIDTH => 63,
        din5_WIDTH => 63,
        din6_WIDTH => 63,
        din7_WIDTH => 63,
        din8_WIDTH => 3,
        dout_WIDTH => 63)
    port map (
        din0 => R_fb_im_q0,
        din1 => R_fb_im_1_q0,
        din2 => R_fb_im_2_q0,
        din3 => R_fb_im_3_q0,
        din4 => R_fb_im_4_q0,
        din5 => R_fb_im_5_q0,
        din6 => R_fb_im_6_q0,
        din7 => R_fb_im_7_q0,
        din8 => trunc_ln6_reg_1079,
        dout => in_im_fu_838_p10);

    flow_control_loop_pipe_sequential_init_U : component real_converter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_102_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln89_fu_632_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_102 <= select_ln89_1_fu_670_p3;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_102 <= ap_const_lv3_0;
                end if;
            end if; 
        end if;
    end process;

    indvar_flatten97_fu_106_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln89_fu_632_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    indvar_flatten97_fu_106 <= add_ln89_fu_638_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    indvar_flatten97_fu_106 <= ap_const_lv6_0;
                end if;
            end if; 
        end if;
    end process;

    j_fu_98_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln89_fu_632_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    j_fu_98 <= add_ln90_fu_742_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    j_fu_98 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;
    process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((icmp_ln89_fu_632_p2 = ap_const_lv1_0) and (ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                trunc_ln6_reg_1079 <= trunc_ln6_fu_738_p1;
                    zext_ln89_reg_907(2 downto 0) <= zext_ln89_fu_678_p1(2 downto 0);
            end if;
        end if;
    end process;
    zext_ln89_reg_907(63 downto 3) <= "0000000000000000000000000000000000000000000000000000000000000";

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
    R_fb_im_1_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_1_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_1_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_1_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_im_2_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_2_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_2_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_2_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_im_3_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_3_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_3_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_3_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_im_4_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_4_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_4_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_4_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_im_5_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_5_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_5_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_5_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_im_6_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_6_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_6_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_6_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_im_7_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_7_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_7_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_7_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_im_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_im_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_im_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_ce0 <= ap_const_logic_1;
        else 
            R_fb_im_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_im_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_im_ce1 <= ap_const_logic_1;
        else 
            R_fb_im_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_1_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_1_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_1_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_1_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_1_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_1_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_2_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_2_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_2_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_2_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_2_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_2_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_3_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_3_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_3_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_3_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_3_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_3_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_4_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_4_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_4_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_4_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_4_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_4_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_4_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_5_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_5_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_5_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_5_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_5_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_5_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_5_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_6_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_6_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_6_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_6_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_6_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_6_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_6_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_7_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_7_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_7_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_7_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_7_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_7_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_7_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    R_fb_re_address0 <= zext_ln89_1_fu_718_p1(3 - 1 downto 0);
    R_fb_re_address1 <= zext_ln89_fu_678_p1(3 - 1 downto 0);

    R_fb_re_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_ce0 <= ap_const_logic_1;
        else 
            R_fb_re_ce0 <= ap_const_logic_0;
        end if; 
    end process;


    R_fb_re_ce1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_fb_re_ce1 <= ap_const_logic_1;
        else 
            R_fb_re_ce1 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_1_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_im_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_1_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_1_d0 <= add_ln9_fu_873_p2;

    Tmp_im_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_5) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_1_we0 <= ap_const_logic_1;
        else 
            Tmp_im_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_2_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_im_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_2_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_2_d0 <= add_ln9_fu_873_p2;

    Tmp_im_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_6) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_2_we0 <= ap_const_logic_1;
        else 
            Tmp_im_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_3_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_im_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_3_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_3_d0 <= add_ln9_fu_873_p2;

    Tmp_im_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_7) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_3_we0 <= ap_const_logic_1;
        else 
            Tmp_im_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_im_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_d0 <= add_ln9_fu_873_p2;

    Tmp_im_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_4) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_we0 <= ap_const_logic_1;
        else 
            Tmp_im_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_1_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_re_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_1_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_1_d0 <= sub_ln8_fu_863_p2;

    Tmp_re_1_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_1) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_1_we0 <= ap_const_logic_1;
        else 
            Tmp_re_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_2_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_re_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_2_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_2_d0 <= sub_ln8_fu_863_p2;

    Tmp_re_2_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_2) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_2_we0 <= ap_const_logic_1;
        else 
            Tmp_re_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_3_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_re_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_3_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_3_d0 <= sub_ln8_fu_863_p2;

    Tmp_re_3_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_3) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_3_we0 <= ap_const_logic_1;
        else 
            Tmp_re_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_address0 <= zext_ln89_reg_907(3 - 1 downto 0);

    Tmp_re_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_d0 <= sub_ln8_fu_863_p2;

    Tmp_re_we0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001, trunc_ln6_reg_1079)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (trunc_ln6_reg_1079 = ap_const_lv3_0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_we0 <= ap_const_logic_1;
        else 
            Tmp_re_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln89_1_fu_664_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv3_1));
    add_ln89_fu_638_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_indvar_flatten97_load) + unsigned(ap_const_lv6_1));
    add_ln90_fu_742_p2 <= std_logic_vector(unsigned(select_ln89_fu_656_p3) + unsigned(ap_const_lv4_1));
    add_ln9_fu_873_p2 <= std_logic_vector(signed(sext_ln18_fu_834_p1) + signed(sext_ln6_1_fu_809_p1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_11001 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_pp0_stage0_subdone <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));
        ap_block_state2_pp0_stage0_iter1 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln89_fu_632_p2)
    begin
        if (((icmp_ln89_fu_632_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, i_fu_102)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_i_load <= ap_const_lv3_0;
        else 
            ap_sig_allocacmp_i_load <= i_fu_102;
        end if; 
    end process;


    ap_sig_allocacmp_indvar_flatten97_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, ap_loop_init, indvar_flatten97_fu_106)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_indvar_flatten97_load <= ap_const_lv6_0;
        else 
            ap_sig_allocacmp_indvar_flatten97_load <= indvar_flatten97_fu_106;
        end if; 
    end process;


    ap_sig_allocacmp_j_load_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, j_fu_98, ap_loop_init)
    begin
        if (((ap_loop_init = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_sig_allocacmp_j_load <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_j_load <= j_fu_98;
        end if; 
    end process;

    empty_18_fu_704_p2 <= (ap_sig_allocacmp_i_load xor ap_const_lv3_4);
    icmp_ln89_fu_632_p2 <= "1" when (ap_sig_allocacmp_indvar_flatten97_load = ap_const_lv6_20) else "0";
    icmp_ln90_fu_650_p2 <= "1" when (ap_sig_allocacmp_j_load = ap_const_lv4_8) else "0";
    p_mid195_fu_698_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_load) + unsigned(ap_const_lv3_5));
    select_ln89_1_fu_670_p3 <= 
        add_ln89_1_fu_664_p2 when (icmp_ln90_fu_650_p2(0) = '1') else 
        ap_sig_allocacmp_i_load;
    select_ln89_2_fu_710_p3 <= 
        p_mid195_fu_698_p2 when (icmp_ln90_fu_650_p2(0) = '1') else 
        empty_18_fu_704_p2;
    select_ln89_fu_656_p3 <= 
        ap_const_lv4_0 when (icmp_ln90_fu_650_p2(0) = '1') else 
        ap_sig_allocacmp_j_load;
        sext_ln18_2_fu_859_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_im_fu_838_p10),64));

        sext_ln18_fu_834_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(in_re_fu_813_p10),64));

        sext_ln6_1_fu_809_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_im_fu_788_p10),64));

        sext_ln6_fu_784_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(a_re_fu_763_p10),64));

    sub_ln8_fu_863_p2 <= std_logic_vector(signed(sext_ln6_fu_784_p1) - signed(sext_ln18_2_fu_859_p1));
    trunc_ln6_fu_738_p1 <= select_ln89_fu_656_p3(3 - 1 downto 0);
    zext_ln89_1_fu_718_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln89_2_fu_710_p3),64));
    zext_ln89_fu_678_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(select_ln89_1_fu_670_p3),64));
end behav;
