-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity real_converter_real_converter_Pipeline_OUT_ROW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    R_out_TREADY : IN STD_LOGIC;
    Tmp_re_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_ce0 : OUT STD_LOGIC;
    Tmp_re_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    Tmp_im_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_ce0 : OUT STD_LOGIC;
    Tmp_im_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    Tmp_re_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_1_ce0 : OUT STD_LOGIC;
    Tmp_re_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    Tmp_im_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_1_ce0 : OUT STD_LOGIC;
    Tmp_im_1_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    Tmp_re_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_2_ce0 : OUT STD_LOGIC;
    Tmp_re_2_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    Tmp_im_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_2_ce0 : OUT STD_LOGIC;
    Tmp_im_2_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    Tmp_re_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_re_3_ce0 : OUT STD_LOGIC;
    Tmp_re_3_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    Tmp_im_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    Tmp_im_3_ce0 : OUT STD_LOGIC;
    Tmp_im_3_q0 : IN STD_LOGIC_VECTOR (63 downto 0);
    R_out_TDATA : OUT STD_LOGIC_VECTOR (511 downto 0);
    R_out_TVALID : OUT STD_LOGIC );
end;


architecture behav of real_converter_real_converter_Pipeline_OUT_ROW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_pp0_stage0 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_boolean_1 : BOOLEAN := true;
    constant ap_const_boolean_0 : BOOLEAN := false;
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv32_1 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000001";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_3F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000111111";
    constant ap_const_lv128_lc_1 : STD_LOGIC_VECTOR (127 downto 0) := "00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv64_0 : STD_LOGIC_VECTOR (63 downto 0) := "0000000000000000000000000000000000000000000000000000000000000000";
    constant ap_const_lv32_2 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000010";

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_pp0_stage0 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_pp0_stage0 : signal is "none";
    signal ap_enable_reg_pp0_iter0 : STD_LOGIC;
    signal ap_enable_reg_pp0_iter1 : STD_LOGIC := '0';
    signal ap_idle_pp0 : STD_LOGIC;
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_block_state2_pp0_stage0_iter1 : BOOLEAN;
    signal ap_block_pp0_stage0_subdone : BOOLEAN;
    signal icmp_ln117_fu_199_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal R_out_TDATA_blk_n : STD_LOGIC;
    signal ap_block_pp0_stage0 : BOOLEAN;
    signal ap_block_pp0_stage0_11001 : BOOLEAN;
    signal zext_ln117_fu_211_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_76 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln117_fu_205_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_1 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_block_pp0_stage0_01001 : BOOLEAN;
    signal res_real_fu_228_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal out_row_packed_cols_fu_234_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal res_real_1_fu_248_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal res_real_2_fu_264_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal res_real_3_fu_280_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal res_real_4_fu_296_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal res_real_6_fu_318_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal res_real_7_fu_334_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln7_fu_254_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln135_1_fu_270_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal trunc_ln135_2_fu_286_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal res_real_5_fu_312_p2 : STD_LOGIC_VECTOR (63 downto 0);
    signal tmp_fu_362_p3 : STD_LOGIC_VECTOR (0 downto 0);
    signal sext_ln138_1_fu_354_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal trunc_ln135_3_fu_302_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln138_2_fu_358_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln138_fu_350_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal sext_ln135_fu_244_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal or_ln_fu_382_p6 : STD_LOGIC_VECTOR (318 downto 0);
    signal sext_ln138_3_fu_396_p1 : STD_LOGIC_VECTOR (319 downto 0);
    signal tmp_1_fu_370_p5 : STD_LOGIC_VECTOR (320 downto 0);
    signal tmp_s_fu_400_p3 : STD_LOGIC_VECTOR (320 downto 0);
    signal tmp_2_fu_414_p4 : STD_LOGIC_VECTOR (61 downto 0);
    signal trunc_ln135_5_fu_324_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln138_4_fu_424_p1 : STD_LOGIC_VECTOR (62 downto 0);
    signal or_ln138_fu_408_p2 : STD_LOGIC_VECTOR (320 downto 0);
    signal or_ln138_1_fu_428_p4 : STD_LOGIC_VECTOR (446 downto 0);
    signal trunc_ln135_6_fu_340_p4 : STD_LOGIC_VECTOR (62 downto 0);
    signal sext_ln138_5_fu_438_p1 : STD_LOGIC_VECTOR (447 downto 0);
    signal or_ln138_5_fu_442_p3 : STD_LOGIC_VECTOR (510 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_enable_pp0 : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_ce_reg : STD_LOGIC;

    component real_converter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component real_converter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_pp0_stage0;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    ap_enable_reg_pp0_iter1_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
            else
                if ((ap_const_logic_1 = ap_condition_exit_pp0_iter0_stage0)) then 
                    ap_enable_reg_pp0_iter1 <= ap_const_logic_0;
                elsif (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
                    ap_enable_reg_pp0_iter1 <= ap_start_int;
                end if; 
            end if;
        end if;
    end process;


    i_fu_76_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then
                if (((icmp_ln117_fu_199_p2 = ap_const_lv1_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1))) then 
                    i_fu_76 <= add_ln117_fu_205_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_76 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_pp0_stage0 => 
                ap_NS_fsm <= ap_ST_fsm_pp0_stage0;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;
        R_out_TDATA <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln138_5_fu_442_p3),512));


    R_out_TDATA_blk_n_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, R_out_TREADY, ap_block_pp0_stage0)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_TDATA_blk_n <= R_out_TREADY;
        else 
            R_out_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    R_out_TVALID_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter1, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            R_out_TVALID <= ap_const_logic_1;
        else 
            R_out_TVALID <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_1_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_im_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_1_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_2_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_im_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_2_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_3_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_im_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_3_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_im_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_im_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_im_ce0 <= ap_const_logic_1;
        else 
            Tmp_im_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_1_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_re_1_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_1_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_2_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_re_2_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_2_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_3_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_re_3_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_3_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    Tmp_re_address0 <= zext_ln117_fu_211_p1(3 - 1 downto 0);

    Tmp_re_ce0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_11001)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_11001) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            Tmp_re_ce0 <= ap_const_logic_1;
        else 
            Tmp_re_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln117_fu_205_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_1) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_pp0_stage0 <= ap_CS_fsm(0);
        ap_block_pp0_stage0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_pp0_stage0_01001_assign_proc : process(ap_enable_reg_pp0_iter1, R_out_TREADY)
    begin
                ap_block_pp0_stage0_01001 <= ((ap_const_logic_0 = R_out_TREADY) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_11001_assign_proc : process(ap_enable_reg_pp0_iter1, R_out_TREADY)
    begin
                ap_block_pp0_stage0_11001 <= ((ap_const_logic_0 = R_out_TREADY) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;


    ap_block_pp0_stage0_subdone_assign_proc : process(ap_enable_reg_pp0_iter1, R_out_TREADY)
    begin
                ap_block_pp0_stage0_subdone <= ((ap_const_logic_0 = R_out_TREADY) and (ap_enable_reg_pp0_iter1 = ap_const_logic_1));
    end process;

        ap_block_state1_pp0_stage0_iter0 <= not((ap_const_boolean_1 = ap_const_boolean_1));

    ap_block_state2_pp0_stage0_iter1_assign_proc : process(R_out_TREADY)
    begin
                ap_block_state2_pp0_stage0_iter1 <= (ap_const_logic_0 = R_out_TREADY);
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone, icmp_ln117_fu_199_p2)
    begin
        if (((icmp_ln117_fu_199_p2 = ap_const_lv1_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0_subdone, ap_loop_exit_ready, ap_done_reg)
    begin
        if (((ap_loop_exit_ready = ap_const_logic_1) and (ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;

    ap_enable_pp0 <= (ap_idle_pp0 xor ap_const_logic_1);
    ap_enable_reg_pp0_iter0 <= ap_start_int;

    ap_idle_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_idle_pp0, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_idle_pp0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;


    ap_idle_pp0_assign_proc : process(ap_enable_reg_pp0_iter0, ap_enable_reg_pp0_iter1)
    begin
        if (((ap_enable_reg_pp0_iter1 = ap_const_logic_0) and (ap_enable_reg_pp0_iter0 = ap_const_logic_0))) then 
            ap_idle_pp0 <= ap_const_logic_1;
        else 
            ap_idle_pp0 <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_enable_reg_pp0_iter0, ap_block_pp0_stage0_subdone)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0_subdone) and (ap_enable_reg_pp0_iter0 = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_1_assign_proc : process(ap_CS_fsm_pp0_stage0, ap_block_pp0_stage0, i_fu_76, ap_loop_init)
    begin
        if (((ap_const_boolean_0 = ap_block_pp0_stage0) and (ap_const_logic_1 = ap_CS_fsm_pp0_stage0) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_1 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_1 <= i_fu_76;
        end if; 
    end process;

    icmp_ln117_fu_199_p2 <= "1" when (ap_sig_allocacmp_i_1 = ap_const_lv4_8) else "0";
    or_ln138_1_fu_428_p4 <= ((trunc_ln135_5_fu_324_p4 & sext_ln138_4_fu_424_p1) & or_ln138_fu_408_p2);
    or_ln138_5_fu_442_p3 <= (trunc_ln135_6_fu_340_p4 & sext_ln138_5_fu_438_p1);
    or_ln138_fu_408_p2 <= (tmp_s_fu_400_p3 or tmp_1_fu_370_p5);
    or_ln_fu_382_p6 <= ((((trunc_ln135_3_fu_302_p4 & sext_ln138_2_fu_358_p1) & ap_const_lv64_0) & sext_ln138_fu_350_p1) & sext_ln135_fu_244_p1);
    out_row_packed_cols_fu_234_p4 <= res_real_fu_228_p2(63 downto 1);
    res_real_1_fu_248_p2 <= std_logic_vector(unsigned(Tmp_im_1_q0) + unsigned(Tmp_re_1_q0));
    res_real_2_fu_264_p2 <= std_logic_vector(unsigned(Tmp_im_2_q0) + unsigned(Tmp_re_2_q0));
    res_real_3_fu_280_p2 <= std_logic_vector(unsigned(Tmp_im_3_q0) + unsigned(Tmp_re_3_q0));
    res_real_4_fu_296_p2 <= std_logic_vector(unsigned(Tmp_re_3_q0) - unsigned(Tmp_im_3_q0));
    res_real_5_fu_312_p2 <= std_logic_vector(unsigned(Tmp_re_2_q0) - unsigned(Tmp_im_2_q0));
    res_real_6_fu_318_p2 <= std_logic_vector(unsigned(Tmp_re_1_q0) - unsigned(Tmp_im_1_q0));
    res_real_7_fu_334_p2 <= std_logic_vector(unsigned(Tmp_re_q0) - unsigned(Tmp_im_q0));
    res_real_fu_228_p2 <= std_logic_vector(unsigned(Tmp_im_q0) + unsigned(Tmp_re_q0));
        sext_ln135_fu_244_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(out_row_packed_cols_fu_234_p4),64));

        sext_ln138_1_fu_354_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln135_1_fu_270_p4),64));

        sext_ln138_2_fu_358_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln135_2_fu_286_p4),64));

        sext_ln138_3_fu_396_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln_fu_382_p6),320));

        sext_ln138_4_fu_424_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(tmp_2_fu_414_p4),63));

        sext_ln138_5_fu_438_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(or_ln138_1_fu_428_p4),448));

        sext_ln138_fu_350_p1 <= std_logic_vector(IEEE.numeric_std.resize(signed(trunc_ln7_fu_254_p4),64));

    tmp_1_fu_370_p5 <= (((tmp_fu_362_p3 & ap_const_lv128_lc_1) & sext_ln138_1_fu_354_p1) & ap_const_lv128_lc_1);
    tmp_2_fu_414_p4 <= res_real_5_fu_312_p2(63 downto 2);
    tmp_fu_362_p3 <= res_real_5_fu_312_p2(1 downto 1);
    tmp_s_fu_400_p3 <= (ap_const_lv1_0 & sext_ln138_3_fu_396_p1);
    trunc_ln135_1_fu_270_p4 <= res_real_2_fu_264_p2(63 downto 1);
    trunc_ln135_2_fu_286_p4 <= res_real_3_fu_280_p2(63 downto 1);
    trunc_ln135_3_fu_302_p4 <= res_real_4_fu_296_p2(63 downto 1);
    trunc_ln135_5_fu_324_p4 <= res_real_6_fu_318_p2(63 downto 1);
    trunc_ln135_6_fu_340_p4 <= res_real_7_fu_334_p2(63 downto 1);
    trunc_ln7_fu_254_p4 <= res_real_1_fu_248_p2(63 downto 1);
    zext_ln117_fu_211_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_1),64));
end behav;
