-- ==============================================================
-- RTL generated by Vitis HLS - High-Level Synthesis from C, C++ and OpenCL v2022.2 (64-bit)
-- Version: 2022.2
-- Copyright (C) Copyright 1986-2022 Xilinx, Inc. All Rights Reserved.
-- 
-- ===========================================================

library IEEE;
use IEEE.std_logic_1164.all;
use IEEE.numeric_std.all;

entity real_converter_real_converter_Pipeline_LOAD_ROW is
port (
    ap_clk : IN STD_LOGIC;
    ap_rst : IN STD_LOGIC;
    ap_start : IN STD_LOGIC;
    ap_done : OUT STD_LOGIC;
    ap_idle : OUT STD_LOGIC;
    ap_ready : OUT STD_LOGIC;
    R_in_TVALID : IN STD_LOGIC;
    R_local_im_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_7_ce0 : OUT STD_LOGIC;
    R_local_im_7_we0 : OUT STD_LOGIC;
    R_local_im_7_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_im_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_6_ce0 : OUT STD_LOGIC;
    R_local_im_6_we0 : OUT STD_LOGIC;
    R_local_im_6_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_im_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_5_ce0 : OUT STD_LOGIC;
    R_local_im_5_we0 : OUT STD_LOGIC;
    R_local_im_5_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_im_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_4_ce0 : OUT STD_LOGIC;
    R_local_im_4_we0 : OUT STD_LOGIC;
    R_local_im_4_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_im_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_3_ce0 : OUT STD_LOGIC;
    R_local_im_3_we0 : OUT STD_LOGIC;
    R_local_im_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_im_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_2_ce0 : OUT STD_LOGIC;
    R_local_im_2_we0 : OUT STD_LOGIC;
    R_local_im_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_im_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_1_ce0 : OUT STD_LOGIC;
    R_local_im_1_we0 : OUT STD_LOGIC;
    R_local_im_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_im_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_im_ce0 : OUT STD_LOGIC;
    R_local_im_we0 : OUT STD_LOGIC;
    R_local_im_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_7_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_7_ce0 : OUT STD_LOGIC;
    R_local_re_7_we0 : OUT STD_LOGIC;
    R_local_re_7_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_6_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_6_ce0 : OUT STD_LOGIC;
    R_local_re_6_we0 : OUT STD_LOGIC;
    R_local_re_6_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_5_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_5_ce0 : OUT STD_LOGIC;
    R_local_re_5_we0 : OUT STD_LOGIC;
    R_local_re_5_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_4_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_4_ce0 : OUT STD_LOGIC;
    R_local_re_4_we0 : OUT STD_LOGIC;
    R_local_re_4_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_3_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_3_ce0 : OUT STD_LOGIC;
    R_local_re_3_we0 : OUT STD_LOGIC;
    R_local_re_3_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_2_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_2_ce0 : OUT STD_LOGIC;
    R_local_re_2_we0 : OUT STD_LOGIC;
    R_local_re_2_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_1_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_1_ce0 : OUT STD_LOGIC;
    R_local_re_1_we0 : OUT STD_LOGIC;
    R_local_re_1_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_local_re_address0 : OUT STD_LOGIC_VECTOR (2 downto 0);
    R_local_re_ce0 : OUT STD_LOGIC;
    R_local_re_we0 : OUT STD_LOGIC;
    R_local_re_d0 : OUT STD_LOGIC_VECTOR (63 downto 0);
    R_in_TDATA : IN STD_LOGIC_VECTOR (1023 downto 0);
    R_in_TREADY : OUT STD_LOGIC );
end;


architecture behav of real_converter_real_converter_Pipeline_LOAD_ROW is 
    constant ap_const_logic_1 : STD_LOGIC := '1';
    constant ap_const_logic_0 : STD_LOGIC := '0';
    constant ap_ST_fsm_state1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv32_0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000000000000";
    constant ap_const_lv1_0 : STD_LOGIC_VECTOR (0 downto 0) := "0";
    constant ap_const_lv1_1 : STD_LOGIC_VECTOR (0 downto 0) := "1";
    constant ap_const_lv4_0 : STD_LOGIC_VECTOR (3 downto 0) := "0000";
    constant ap_const_lv4_8 : STD_LOGIC_VECTOR (3 downto 0) := "1000";
    constant ap_const_lv4_1 : STD_LOGIC_VECTOR (3 downto 0) := "0001";
    constant ap_const_lv32_40 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001000000";
    constant ap_const_lv32_7F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000001111111";
    constant ap_const_lv32_80 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010000000";
    constant ap_const_lv32_BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000010111111";
    constant ap_const_lv32_C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011000000";
    constant ap_const_lv32_FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000011111111";
    constant ap_const_lv32_100 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100000000";
    constant ap_const_lv32_13F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000100111111";
    constant ap_const_lv32_140 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101000000";
    constant ap_const_lv32_17F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000101111111";
    constant ap_const_lv32_180 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110000000";
    constant ap_const_lv32_1BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000110111111";
    constant ap_const_lv32_1C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111000000";
    constant ap_const_lv32_1FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000000111111111";
    constant ap_const_lv32_200 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000000000";
    constant ap_const_lv32_23F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001000111111";
    constant ap_const_lv32_240 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001000000";
    constant ap_const_lv32_27F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001001111111";
    constant ap_const_lv32_280 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010000000";
    constant ap_const_lv32_2BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001010111111";
    constant ap_const_lv32_2C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011000000";
    constant ap_const_lv32_2FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001011111111";
    constant ap_const_lv32_300 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100000000";
    constant ap_const_lv32_33F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001100111111";
    constant ap_const_lv32_340 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101000000";
    constant ap_const_lv32_37F : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001101111111";
    constant ap_const_lv32_380 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110000000";
    constant ap_const_lv32_3BF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001110111111";
    constant ap_const_lv32_3C0 : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111000000";
    constant ap_const_lv32_3FF : STD_LOGIC_VECTOR (31 downto 0) := "00000000000000000000001111111111";
    constant ap_const_boolean_1 : BOOLEAN := true;

attribute shreg_extract : string;
    signal ap_CS_fsm : STD_LOGIC_VECTOR (0 downto 0) := "1";
    attribute fsm_encoding : string;
    attribute fsm_encoding of ap_CS_fsm : signal is "none";
    signal ap_CS_fsm_state1 : STD_LOGIC;
    attribute fsm_encoding of ap_CS_fsm_state1 : signal is "none";
    signal icmp_ln56_fu_356_p2 : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_block_state1_pp0_stage0_iter0 : BOOLEAN;
    signal ap_condition_exit_pp0_iter0_stage0 : STD_LOGIC;
    signal ap_loop_exit_ready : STD_LOGIC;
    signal ap_ready_int : STD_LOGIC;
    signal R_in_TDATA_blk_n : STD_LOGIC;
    signal zext_ln56_fu_368_p1 : STD_LOGIC_VECTOR (63 downto 0);
    signal i_fu_130 : STD_LOGIC_VECTOR (3 downto 0);
    signal add_ln56_fu_362_p2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_loop_init : STD_LOGIC;
    signal ap_sig_allocacmp_i_2 : STD_LOGIC_VECTOR (3 downto 0);
    signal ap_done_reg : STD_LOGIC := '0';
    signal ap_continue_int : STD_LOGIC;
    signal ap_done_int : STD_LOGIC;
    signal ap_NS_fsm : STD_LOGIC_VECTOR (0 downto 0);
    signal ap_ST_fsm_state1_blk : STD_LOGIC;
    signal ap_start_int : STD_LOGIC;
    signal ap_condition_327 : BOOLEAN;
    signal ap_ce_reg : STD_LOGIC;

    component real_converter_flow_control_loop_pipe_sequential_init IS
    port (
        ap_clk : IN STD_LOGIC;
        ap_rst : IN STD_LOGIC;
        ap_start : IN STD_LOGIC;
        ap_ready : OUT STD_LOGIC;
        ap_done : OUT STD_LOGIC;
        ap_start_int : OUT STD_LOGIC;
        ap_loop_init : OUT STD_LOGIC;
        ap_ready_int : IN STD_LOGIC;
        ap_loop_exit_ready : IN STD_LOGIC;
        ap_loop_exit_done : IN STD_LOGIC;
        ap_continue_int : OUT STD_LOGIC;
        ap_done_int : IN STD_LOGIC );
    end component;



begin
    flow_control_loop_pipe_sequential_init_U : component real_converter_flow_control_loop_pipe_sequential_init
    port map (
        ap_clk => ap_clk,
        ap_rst => ap_rst,
        ap_start => ap_start,
        ap_ready => ap_ready,
        ap_done => ap_done,
        ap_start_int => ap_start_int,
        ap_loop_init => ap_loop_init,
        ap_ready_int => ap_ready_int,
        ap_loop_exit_ready => ap_condition_exit_pp0_iter0_stage0,
        ap_loop_exit_done => ap_done_int,
        ap_continue_int => ap_continue_int,
        ap_done_int => ap_done_int);





    ap_CS_fsm_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_CS_fsm <= ap_ST_fsm_state1;
            else
                ap_CS_fsm <= ap_NS_fsm;
            end if;
        end if;
    end process;


    ap_done_reg_assign_proc : process(ap_clk)
    begin
        if (ap_clk'event and ap_clk =  '1') then
            if (ap_rst = '1') then
                ap_done_reg <= ap_const_logic_0;
            else
                if ((ap_continue_int = ap_const_logic_1)) then 
                    ap_done_reg <= ap_const_logic_0;
                elsif ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
                    ap_done_reg <= ap_const_logic_1;
                end if; 
            end if;
        end if;
    end process;


    i_fu_130_assign_proc : process (ap_clk)
    begin
        if (ap_clk'event and ap_clk = '1') then
            if ((ap_const_boolean_1 = ap_condition_327)) then
                if ((icmp_ln56_fu_356_p2 = ap_const_lv1_0)) then 
                    i_fu_130 <= add_ln56_fu_362_p2;
                elsif ((ap_loop_init = ap_const_logic_1)) then 
                    i_fu_130 <= ap_const_lv4_0;
                end if;
            end if; 
        end if;
    end process;

    ap_NS_fsm_assign_proc : process (ap_CS_fsm, ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        case ap_CS_fsm is
            when ap_ST_fsm_state1 => 
                ap_NS_fsm <= ap_ST_fsm_state1;
            when others =>  
                ap_NS_fsm <= "X";
        end case;
    end process;

    R_in_TDATA_blk_n_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_1) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_in_TDATA_blk_n <= R_in_TVALID;
        else 
            R_in_TDATA_blk_n <= ap_const_logic_1;
        end if; 
    end process;


    R_in_TREADY_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_in_TREADY <= ap_const_logic_1;
        else 
            R_in_TREADY <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_1_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_1_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_1_ce0 <= ap_const_logic_1;
        else 
            R_local_im_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_1_d0 <= R_in_TDATA(255 downto 192);

    R_local_im_1_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_1_we0 <= ap_const_logic_1;
        else 
            R_local_im_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_2_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_2_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_2_ce0 <= ap_const_logic_1;
        else 
            R_local_im_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_2_d0 <= R_in_TDATA(383 downto 320);

    R_local_im_2_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_2_we0 <= ap_const_logic_1;
        else 
            R_local_im_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_3_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_3_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_3_ce0 <= ap_const_logic_1;
        else 
            R_local_im_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_3_d0 <= R_in_TDATA(511 downto 448);

    R_local_im_3_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_3_we0 <= ap_const_logic_1;
        else 
            R_local_im_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_4_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_4_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_4_ce0 <= ap_const_logic_1;
        else 
            R_local_im_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_4_d0 <= R_in_TDATA(639 downto 576);

    R_local_im_4_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_4_we0 <= ap_const_logic_1;
        else 
            R_local_im_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_5_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_5_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_5_ce0 <= ap_const_logic_1;
        else 
            R_local_im_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_5_d0 <= R_in_TDATA(767 downto 704);

    R_local_im_5_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_5_we0 <= ap_const_logic_1;
        else 
            R_local_im_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_6_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_6_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_6_ce0 <= ap_const_logic_1;
        else 
            R_local_im_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_6_d0 <= R_in_TDATA(895 downto 832);

    R_local_im_6_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_6_we0 <= ap_const_logic_1;
        else 
            R_local_im_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_7_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_7_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_7_ce0 <= ap_const_logic_1;
        else 
            R_local_im_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_7_d0 <= R_in_TDATA(1023 downto 960);

    R_local_im_7_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_7_we0 <= ap_const_logic_1;
        else 
            R_local_im_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_im_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_ce0 <= ap_const_logic_1;
        else 
            R_local_im_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_im_d0 <= R_in_TDATA(127 downto 64);

    R_local_im_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_im_we0 <= ap_const_logic_1;
        else 
            R_local_im_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_1_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_1_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_1_ce0 <= ap_const_logic_1;
        else 
            R_local_re_1_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_1_d0 <= R_in_TDATA(191 downto 128);

    R_local_re_1_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_1_we0 <= ap_const_logic_1;
        else 
            R_local_re_1_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_2_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_2_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_2_ce0 <= ap_const_logic_1;
        else 
            R_local_re_2_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_2_d0 <= R_in_TDATA(319 downto 256);

    R_local_re_2_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_2_we0 <= ap_const_logic_1;
        else 
            R_local_re_2_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_3_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_3_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_3_ce0 <= ap_const_logic_1;
        else 
            R_local_re_3_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_3_d0 <= R_in_TDATA(447 downto 384);

    R_local_re_3_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_3_we0 <= ap_const_logic_1;
        else 
            R_local_re_3_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_4_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_4_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_4_ce0 <= ap_const_logic_1;
        else 
            R_local_re_4_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_4_d0 <= R_in_TDATA(575 downto 512);

    R_local_re_4_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_4_we0 <= ap_const_logic_1;
        else 
            R_local_re_4_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_5_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_5_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_5_ce0 <= ap_const_logic_1;
        else 
            R_local_re_5_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_5_d0 <= R_in_TDATA(703 downto 640);

    R_local_re_5_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_5_we0 <= ap_const_logic_1;
        else 
            R_local_re_5_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_6_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_6_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_6_ce0 <= ap_const_logic_1;
        else 
            R_local_re_6_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_6_d0 <= R_in_TDATA(831 downto 768);

    R_local_re_6_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_6_we0 <= ap_const_logic_1;
        else 
            R_local_re_6_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_7_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_7_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_7_ce0 <= ap_const_logic_1;
        else 
            R_local_re_7_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_7_d0 <= R_in_TDATA(959 downto 896);

    R_local_re_7_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_7_we0 <= ap_const_logic_1;
        else 
            R_local_re_7_we0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_address0 <= zext_ln56_fu_368_p1(3 - 1 downto 0);

    R_local_re_ce0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_ce0 <= ap_const_logic_1;
        else 
            R_local_re_ce0 <= ap_const_logic_0;
        end if; 
    end process;

    R_local_re_d0 <= R_in_TDATA(64 - 1 downto 0);

    R_local_re_we0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            R_local_re_we0 <= ap_const_logic_1;
        else 
            R_local_re_we0 <= ap_const_logic_0;
        end if; 
    end process;

    add_ln56_fu_362_p2 <= std_logic_vector(unsigned(ap_sig_allocacmp_i_2) + unsigned(ap_const_lv4_1));
    ap_CS_fsm_state1 <= ap_CS_fsm(0);

    ap_ST_fsm_state1_blk_assign_proc : process(R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) then 
            ap_ST_fsm_state1_blk <= ap_const_logic_1;
        else 
            ap_ST_fsm_state1_blk <= ap_const_logic_0;
        end if; 
    end process;


    ap_block_state1_pp0_stage0_iter0_assign_proc : process(R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
                ap_block_state1_pp0_stage0_iter0 <= ((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)));
    end process;


    ap_condition_327_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
                ap_condition_327 <= (not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1));
    end process;


    ap_condition_exit_pp0_iter0_stage0_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (icmp_ln56_fu_356_p2 = ap_const_lv1_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_1;
        else 
            ap_condition_exit_pp0_iter0_stage0 <= ap_const_logic_0;
        end if; 
    end process;


    ap_done_int_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_loop_exit_ready, ap_done_reg, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_loop_exit_ready = ap_const_logic_1) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_done_int <= ap_const_logic_1;
        else 
            ap_done_int <= ap_done_reg;
        end if; 
    end process;


    ap_idle_assign_proc : process(ap_CS_fsm_state1, ap_start_int)
    begin
        if (((ap_start_int = ap_const_logic_0) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_idle <= ap_const_logic_1;
        else 
            ap_idle <= ap_const_logic_0;
        end if; 
    end process;

    ap_loop_exit_ready <= ap_condition_exit_pp0_iter0_stage0;

    ap_ready_int_assign_proc : process(ap_CS_fsm_state1, R_in_TVALID, icmp_ln56_fu_356_p2, ap_start_int)
    begin
        if ((not(((ap_start_int = ap_const_logic_0) or ((ap_const_logic_0 = R_in_TVALID) and (icmp_ln56_fu_356_p2 = ap_const_lv1_0)))) and (ap_const_logic_1 = ap_CS_fsm_state1))) then 
            ap_ready_int <= ap_const_logic_1;
        else 
            ap_ready_int <= ap_const_logic_0;
        end if; 
    end process;


    ap_sig_allocacmp_i_2_assign_proc : process(ap_CS_fsm_state1, i_fu_130, ap_loop_init)
    begin
        if (((ap_const_logic_1 = ap_CS_fsm_state1) and (ap_loop_init = ap_const_logic_1))) then 
            ap_sig_allocacmp_i_2 <= ap_const_lv4_0;
        else 
            ap_sig_allocacmp_i_2 <= i_fu_130;
        end if; 
    end process;

    icmp_ln56_fu_356_p2 <= "1" when (ap_sig_allocacmp_i_2 = ap_const_lv4_8) else "0";
    zext_ln56_fu_368_p1 <= std_logic_vector(IEEE.numeric_std.resize(unsigned(ap_sig_allocacmp_i_2),64));
end behav;
